
<script>
export default {data() {return {};}}
</script>

<template><div><div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>无战技</p><br>战技：无战技<br><br>武器没有战技。<br>如果另一边的武器具备战技，<br>会使用那一边的战技。</div><div class="t"><p>戦技なし</p><br>戦技なし<br><br>この武器は戦技を持たない<br>もう一方の武器に戦技があれば<br>常にそれが使用される<br></div><div class="t"><p>No Skill</p><br>No skill.<br><br>This armament has no skill.<br>If the armament in the other hand has a skill, that skill will be used instead.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>狮子斩</p><br>战技：狮子斩<br><br>与拉塔恩将军并肩作战的<br>红狮子军队所使用的战技。<br>能朝前方跳跃，一边旋身一边以武器敲击。</div><div class="t"><p>獅子斬り</p><br>戦技「獅子斬り」<br><br>将軍ラダーンと共に戦った、赤獅子の軍勢の戦技<br>前方に跳躍し、回転しながら武器を叩き付ける<br></div><div class="t"><p>Lion's Claw</p><br>Skill: Lion's Claw<br><br>Skill of the Redmanes, who fought alongside General Radahn.<br>Somersault forwards, striking foes with armament.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>贯穿</p><br>战技：贯穿<br><br>突刺武器对付持盾敌人时的战技。<br>蓄力之后，大幅度向前跨出<br>使出浑身一刺，从正面突破防御。</div><div class="t"><p>貫通突き</p><br>戦技「貫通突き」<br><br>刺突武器で盾に対するための戦技<br>力を溜め、大きく踏み込む強烈な突きは<br>ガードを正面から貫く<br></div><div class="t"><p>Impaling Thrust</p><br>Skill: Impaling Thrust<br><br>Skill that lets piercing armaments overcome enemy shields. Build power, then lunge forward for a strong thrust that pierces an enemy's guard.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>突刺</p><br>战技：突刺<br><br>“血指猎人”尤拉的战技。<br>举起武器与地面平行，再一口气贯穿敌人。<br>此战技无法用防御挡下。</div><div class="t"><p>牙突き</p><br>戦技「牙突き」<br><br>血の指の狩人、ユラの戦技<br>刃を水平に掲げ、一気に刺し貫く<br>これをガードすることはできない<br></div><div class="t"><p>Piercing Fang</p><br>Skill: Piercing Fang<br><br>Skill used by Yura, the Bloody Finger Hunter.<br>Starting with the blade held horizontally, make a powerful thrust that cannot be blocked.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>回旋斩</p><br>战技：回旋斩<br><br>拥有高灵巧的剑士们使用的战技。<br>能大幅旋转身体，砍向敌人。<br>再次发动能使出追击。</div><div class="t"><p>回転斬り</p><br>戦技「回転斬り」<br><br>技量に優れた剣士たちの戦技<br>大きく体を回転させて敵を斬りつける<br>また、追加入力で追撃に繋げられる<br></div><div class="t"><p>Spinning Slash</p><br>Skill: Spinning Slash<br><br>Skill favored by dexterous warriors.<br>Slash foes as your body spins. Additional input allows for a follow-up attack.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>突击</p><br>战技：突击<br><br>武器及腰摆出架式，再一口气向前冲的战技。<br>前进到极限后能使出突刺攻击。<br>持续发动能增加移动距离。</div><div class="t"><p>突撃</p><br>戦技「突撃」<br><br>腰だめに武器を構え、一気に前進する戦技<br>その勢いのまま、最後に突きを放つ<br>長押しで前進距離を伸ばすことができる<br></div><div class="t"><p>Charge Forth</p><br>Skill: Charge Forth<br><br>Quickly charge forward with the armament at the hip, carrying the momentum into a thrust.<br>Hold to cover a greater distance.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>箭步（上砍）</p><br>战技：箭步（上砍）<br><br>举起武器摆出架式，稳住姿势压低身形，<br>瞬间提升强韧度的战技。<br>发动后接着使出重攻击，能上砍攻击。</div><div class="t"><p>踏み込み（斬り上げ）</p><br>戦技「踏み込み（斬り上げ）」<br><br>武器を構え、体を固めて低く踏み込み<br>瞬間的に、強靭度を高める戦技<br>また、強攻撃で斬り上げに繋げられる<br></div><div class="t"><p>Stamp (Upward Cut)</p><br>Skill: Stamp (Upward Cut)<br><br>Brace armament and step into a low stance that prevents recoil from most enemy attacks.<br>Follow up with a strong attack for an upward strike.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>箭步（回旋斩）</p><br>战技：箭步（回旋斩）<br><br>举起武器摆出架式，稳住姿势压低身形，<br>瞬间提升强韧度的战技。<br>发动后接着使出重攻击，能回旋斩。</div><div class="t"><p>踏み込み（回転薙ぎ）</p><br>戦技「踏み込み（回転薙ぎ）」<br><br>武器を構え、体を固めて低く踏み込み<br>瞬間的に、強靭度を高める戦技<br>また、強攻撃で回転薙ぎに繋げられる<br></div><div class="t"><p>Stamp (Sweep)</p><br>Skill: Stamp (Sweep)<br><br>Brace armament and step into a low stance that prevents recoil from most enemy attacks.<br>Follow up with a strong attack for a sweeping strike.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>鲜血征收</p><br>战技：鲜血征收<br><br>鲜血君王分享的力量，血盟战技之一。<br>旋身之后，使出多重的突刺连击。<br>能夺取受攻击对象的鲜血与血量。</div><div class="t"><p>血の徴収</p><br>戦技「血の徴収」<br><br>血の君主の分け与える力、血盟戦技のひとつ<br>回転から、一気に連撃の突きを繰り出し<br>攻撃した相手から、血と共にＨＰを奪う<br></div><div class="t"><p>Blood Tax</p><br>Skill: Blood Tax<br><br>Blood Oath skill granted by the Lord of Blood.<br>Twist to build power, then unleash a flurry of thrusts that rob the target of both their blood and their HP.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>连击</p><br>战技：连击<br><br>旋身之后，使出连续突刺的战技。</div><div class="t"><p>連続突き</p><br>戦技「連続突き」<br><br>体を回転させ、そこから一気に<br>連撃の突きを繰り出す戦技<br></div><div class="t"><p>Repeating Thrust</p><br>Skill: Repeating Thrust<br><br>Twist to build power, then unleash a flurry of thrusts.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>盲击</p><br>战技：盲击<br><br>不间断、任意挥动武器的战技。<br>持续发动的期间能一直攻击，<br>接着使出轻攻击或重攻击，能追加攻击。</div><div class="t"><p>乱撃</p><br>戦技「乱撃」<br><br>無造作に武器を振り続ける戦技<br>長押している間は、ずっと攻撃を継続し<br>通常攻撃および強攻撃で追撃に繋げられる<br></div><div class="t"><p>Wild Strikes</p><br>Skill: Wild Strikes<br><br>Swing armament with wild abandon.<br>Hold to continue swinging. Can be followed up with a normal or strong attack.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>回旋击</p><br>战技：回旋击<br><br>大幅度旋转长柄武器的战技。<br>持续发动的期间能一直攻击，<br>接着使出轻攻击或重攻击，能追加攻击。<br>旋转武器时，能拨开箭等等的远攻道具。</div><div class="t"><p>回転撃</p><br>戦技「回転撃」<br><br>長柄の武器を、大きく回し続ける戦技<br>長押している間は、ずっと攻撃を継続し<br>通常攻撃および強攻撃で追撃に繋げられる<br>また回転中は、矢などの飛び道具を逸らせる<br></div><div class="t"><p>Spinning Strikes</p><br>Skill: Spinning Strikes<br><br>Polearm skill that performs continuous spinning attacks. Hold to continue the attack. Can be followed up with a normal or strong attack. Nullifies projectiles such as arrows while spinning.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>二连斩</p><br>战技：二连斩<br><br>杰出剑士的战技。<br>压低身形后，使出连续的交错斩击。<br>再次发动能使出最多两次的追击。</div><div class="t"><p>二連斬り</p><br>戦技「二連斬り」<br><br>卓越した剣士の戦技<br>低い構えから、交差する斬撃を繰り出す<br>追加入力で、二度まで追撃に繋げられる<br></div><div class="t"><p>Double Slash</p><br>Skill: Double Slash<br><br>Skill of superior swordsmen.<br>Perform a crossing slash attack from a low stance.<br>Repeated inputs allow for up to two follow-up attacks.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>主教冲锋</p><br>战技：主教冲锋<br><br>将武器敲向地面，形成猛烈燃烧的火焰，<br>再顺势向前推进的战技。<br>持续发动的期间能一直向前推进。</div><div class="t"><p>司教の突進</p><br>戦技「司教の突進」<br><br>武器を地面に叩きつけ、激しい炎を生じ<br>そのまま突進していく戦技<br>長押ししている間は、止まることがない<br></div><div class="t"><p>Prelate's Charge</p><br>Skill: Prelate's Charge<br><br>Slam armament into the ground to create a surge of flames, then charge in.<br>Hold to continue the charge.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>居合</p><br>战技：居合<br><br>芦苇之地的剑客继承而来的战技。<br>收刀入腰间刀鞘，摆出架式后静止不动，<br>接着使出轻攻击或重攻击，能高速斩击。</div><div class="t"><p>居合</p><br>戦技「居合」<br><br>葦の地の剣客に伝わる戦技<br>刀身を鞘に収め、腰だめに静かに構え<br>通常攻撃および強攻撃で、高速の斬撃に繋げる<br></div><div class="t"><p>Unsheathe</p><br>Skill: Unsheathe<br><br>Skill of swordsmen from the Land of Reeds.<br>Sheathe blade, holding it at the hip in a composed stance.<br>Follow up with a normal or strong attack to perform a swift slash attack.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>准备架式</p><br>战技：准备架式<br><br>举起剑与地面平行，接着使出攻击的战技。<br>轻攻击能使出由下而上，突破防御的斩击。<br>重攻击能向前冲刺、突刺攻击。</div><div class="t"><p>構え</p><br>戦技「構え」<br><br>剣を水平に構え、攻撃に繋げる戦技<br>通常攻撃で、ガードを崩す斬り上げ<br>強攻撃で走り込む突きに派生する<br></div><div class="t"><p>Square Off</p><br>Skill: Square Off<br><br>This skill starts with the sword held level.<br>Follow up with a normal attack to slash upwards through enemy's guard, or a strong attack to perform a running thrust.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>狩猎巨人</p><br>战技：狩猎巨人<br><br>挑战体型比自己大的敌人而有的战技。<br>压低身形稳住姿势，向前踏出，<br>接着顺势由下而上突刺敌人。</div><div class="t"><p>巨人狩り</p><br>戦技「巨人狩り」<br><br>自らよりも大きな敵に、挑むための戦技<br>低い姿勢から、体を固めて一歩踏み込み<br>そのまま一気に、下から敵を突き上げる<br></div><div class="t"><p>Giant Hunt</p><br>Skill: Giant Hunt<br><br>Skill developed for confronting gigantic foes.<br>Step forward from a low stance, carrying the momentum into a sudden upward thrust.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>火把攻击</p><br>战技：火把攻击<br><br>将火把的火焰往前突刺，燃烧敌人的战技。<br>对不耐火的敌人很有效。</div><div class="t"><p>松明攻撃</p><br>戦技「松明攻撃」<br><br>松明の炎を前方に突き出し、敵を焼く戦技<br>火に弱い敵には有効である<br></div><div class="t"><p>Torch Attack</p><br>Skill: Torch Attack<br><br>Thrust torch forward to set foes ablaze.<br>This skill is especially effective against foes who are weak to fire.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>罗蕾塔的斩击</p><br>战技：罗蕾塔的斩击<br><br>禁卫骑士罗蕾塔的战技。<br>向前跳的同时，将辉石的魔力灌入剑身，<br>再加快速度瞬间斩下。</div><div class="t"><p>ローレッタの斬撃</p><br>戦技「ローレッタの斬撃」<br><br>親衛騎士ローレッタの戦技<br>前方に跳躍し、刃に輝石の魔力を宿し<br>加速して一気に斬り下ろす<br></div><div class="t"><p>Loretta's Slash</p><br>Skill: Loretta's Slash<br><br>Skill of Loretta the Royal Knight.<br>Leap forward, imbuing the blade with glintstone, then descend, accelerating into a sweeping slash.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>双吻毒蛾</p><br>战技：双吻毒蛾<br><br>在剑刃涂上强效毒，砍向敌人的战技。<br>对上陷入中毒状态的敌人，<br>如果成功使出追击，能一口气给予大伤害。</div><div class="t"><p>毒蛾は二度舞う</p><br>戦技「毒蛾は二度舞う」<br><br>刃に強毒を纏わせ、斬りつける戦技<br>既に毒状態の敵に追撃が成功すれば<br>一気に大ダメージを与える<br></div><div class="t"><p>Poison Moth Flight</p><br>Skill: Poison Moth Flight<br><br>Slash with a poison-infused blade.<br>If the follow-up strike lands on a poisoned foe, it will deal significant damage.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>转啊转</p><br>战技：转啊转<br><br>卡利亚公主们防身用的战技。<br>将武器浮在自身前方高速旋转，<br>触碰到的人物会受到连击。</div><div class="t"><p>回れ回れ</p><br>戦技「回れ回れ」<br><br>カーリアの王女たちの護身の戦技<br>武器を前方に浮かせ、高速に回転させる<br>それは、触れる者に連撃をなす<br></div><div class="t"><p>Spinning Weapon</p><br>Skill: Spinning Weapon<br><br>Defensive skill employed by Carian princesses.<br>Lifts armament into mid-air, then makes it spin violently. Those it touches will suffer successive attacks.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>风暴袭击</p><br>战技：风暴袭击<br><br>史东薇尔的风暴战技之一。<br>缠绕着风暴向前跳，将武器向下刺。<br>突刺攻击后也会形成风暴。</div><div class="t"><p>嵐の襲撃</p><br>戦技「嵐の襲撃」<br><br>ストームヴィルの嵐の戦技のひとつ<br>嵐と共に前方に跳躍し、武器を突き下ろし<br>その攻撃もまた、嵐を発生させる<br></div><div class="t"><p>Storm Assault</p><br>Skill: Storm Assault<br><br>One of the skills that channel the tempests of Stormveil.<br>Leap forward through surrounding storm winds and thrust armament downward. The attack will produce more storm winds at the point of impact.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>唤起风暴</p><br>战技：唤起风暴<br><br>史东薇尔的风暴战技之一。<br>能挥舞武器，在自身周围唤起风暴。<br>再次发动能使出最多两次的追击。</div><div class="t"><p>嵐呼び</p><br>戦技「嵐呼び」<br><br>ストームヴィルの嵐の戦技のひとつ<br>武器を振り回し、自らの周囲に嵐を呼ぶ<br>追加入力で、二度まで追撃に繋げられる<br></div><div class="t"><p>Stormcaller</p><br>Skill: Stormcaller<br><br>One of the skills that channel the tempests of Stormveil. Spin armament to create surrounding storm winds. Repeated inputs allow for up to two follow-up attacks.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>剑舞</p><br>战技：剑舞<br><br>一边迅速向前推进，<br>一边使出连续旋身上砍的战技。<br>再次发动能使出迅速下砍。</div><div class="t"><p>剣舞</p><br>戦技「剣舞」<br><br>鋭く一気に前進しながら<br>連続で回転斬り上げを繰り出す戦技<br>追加入力で、鋭い斬り下ろしに繋げられる<br></div><div class="t"><p>Sword Dance</p><br>Skill: Sword Dance<br><br>Quickly close in to perform a series of spinning upward slashes.<br>Follow up with an additional input to finish with a downward slash.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>回旋锁链</p><br>战技：回旋锁链<br><br>高速旋转连枷打击部位的战技。<br>发动后使出轻攻击或重攻击，能顺势追击。</div><div class="t"><p>鎖回し</p><br>戦技「鎖回し」<br><br>フレイルの打撃部を、高速で回転させる戦技<br>通常攻撃および強攻撃で<br>その勢いを活かした、追撃に繋げられる<br></div><div class="t"><p>Spinning Chain</p><br>Skill: Spinning Chain<br><br>Spins the striking part of a flail at high speed to attack.<br>Follow up with a normal or strong attack to link the momentum of this skill into a successive attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>辉剑圆阵</p><br>战技：辉剑圆阵<br><br>侍奉卡利亚王室的魔法骑士们使用的战技。<br>让魔力辉剑浮空围成半圆，自动攻击敌人。<br>发动后接着使出重攻击，<br>能向前大幅跨出、突刺攻击。</div><div class="t"><p>輝剣の円陣</p><br>戦技「輝剣の円陣」<br><br>カーリア王家に仕えた魔術騎士たちの戦技<br>魔力の輝剣を半円に浮遊させ、自動的に攻撃させる<br>強攻撃で、大きく踏み込む突きに繋げられる<br></div><div class="t"><p>Glintblade Phalanx</p><br>Skill: Glintblade Phalanx<br><br>Skill used by the enchanted knights who served the Carian royal family. Form an arch of magic glintblades overhead, which will attack foes automatically. Follow up with a strong attack to chain this skill into a lunging thrust.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>冰枪</p><br>战技：冰枪<br><br>侍奉“月之公主”菈妮的战士使用的战技。<br>旋转武器之余唤出寒气，<br>再顺势使出突刺，释放冰枪。</div><div class="t"><p>氷槍</p><br>戦技「氷槍」<br><br>月の王女、ラニに仕えた戦士の戦技<br>回転させた武器に冷気を呼び<br>そのまま突き、氷の槍を放つ<br></div><div class="t"><p>Ice Spear</p><br>Skill: Ice Spear<br><br>Skill of the warriors who served Lunar Princess Ranni.<br>Spin armament to release cold magic, then channel it into a piercing spear of ice.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>辉石魔砾</p><br>战技：辉石魔砾<br><br>能施展同名辉石魔法的战技。<br>发动后接着使出重攻击，能大幅向前跨出，<br>使出含有辉石魔力的突刺攻击。</div><div class="t"><p>輝石のつぶて</p><br>戦技「輝石のつぶて」<br><br>同名の輝石魔術を用いる戦技<br>強攻撃で、大きく踏み込む突きに繋げられ<br>その攻撃は輝石の魔力を残している<br></div><div class="t"><p>Glintstone Pebble</p><br>Skill: Glintstone Pebble<br><br>Skill that employs the glintstone sorcery of the same name.<br>Follow up with a strong attack to chain this skill into a lunging thrust, performed while the armament is still imbued with glintstone.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>鲜血斩击</p><br>战技：鲜血斩击<br><br>鲜血君王分享的力量，血盟战技之一。<br>压低身形，将自身的血液布满剑身，<br>使出大范围撕裂敌人的血刃。</div><div class="t"><p>血の斬撃</p><br>戦技「血の斬撃」<br><br>血の君主の分け与える力、血盟戦技のひとつ<br>体を沈め、刀身に自らの血を纏わせ<br>血の刃で広範囲を切り裂く<br></div><div class="t"><p>Bloody Slash</p><br>Skill: Bloody Slash<br><br>Blood Oath skill granted by the Lord of Blood.<br>From a low stance, coat the blade in your own blood to unleash a rending blood slash in a wide arc.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>夺命拳</p><br>战技：夺命拳<br><br>精通气的专家使用的战技。<br>只对有着人类之身的敌人有效。<br>将气缓慢缠绕拳头之后再出拳，<br>能让碰触的人昏倒，夺取血量。</div><div class="t"><p>命奪拳</p><br>戦技「命奪拳」<br><br>気を極めた達人の戦技。人の類にしか効果がない<br>ゆっくりと気を纏った拳を突き出し<br>触れた者を昏倒させ、ＨＰを奪う<br></div><div class="t"><p>Lifesteal Fist</p><br>Skill: Lifesteal Fist<br><br>Skill that demonstrates mastery of the art of controlling vital energies.<br>A slow, controlled punch with an energy-infused fist that renders foes unconscious and steals their HP. Only effective against foes of human build.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>熔岩火浆</p><br>战技：熔岩火浆<br><br>侍奉火山官邸的骑士们使用的战技。<br>将武器敲向地面，形成滚烫熔岩，<br>在拔起武器的同时，熔岩随之喷出。</div><div class="t"><p>溶岩噴火</p><br>戦技「溶岩噴火」<br><br>火山館に仕えた騎士たちの戦技<br>武器を叩きつけた地面に、滾る溶岩を生じ<br>引き抜きと共にそれを噴き上げる<br></div><div class="t"><p>Eruption</p><br>Skill: Eruption<br><br>Skill of the knights who serve at Volcano Manor.<br>Slam armament into the ground, spawning roiling lava which spouts up upon release.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>祈祷一击</p><br>战技：祈祷一击<br><br>伴随祈祷高举武器，再敲向地面的战技。<br>当那一记诚挚的攻击命中敌人，<br>能恢复包含周围我方人物的血量。</div><div class="t"><p>祈りの一撃</p><br>戦技「祈りの一撃」<br><br>祈りと共に武器を掲げ、地面に叩き付ける戦技<br>その真摯な一撃が敵に命中すれば<br>周囲の味方を含めて、ＨＰを回復する<br></div><div class="t"><p>Prayerful Strike</p><br>Skill: Prayerful Strike<br><br>Raise armament aloft in prayer, then slam it into the ground.<br>This inspired blow restores HP to the self and nearby allies if it successfully hits.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>重力</p><br>战技：重力<br><br>源自拥有石质皮肤的白王的战技。<br>将武器刺入地面，产生重力波，<br>能给予敌人伤害，同时将对方拉近自己。</div><div class="t"><p>グラビタス</p><br>戦技「グラビタス」<br><br>石の肌を持つ白王に由来する戦技<br>武器を地面に刺し、重力波を発生させ<br>ダメージを与えると共に、敵を引き寄せる<br></div><div class="t"><p>Gravitas</p><br>Skill: Gravitas<br><br>Skill originating from the Alabaster Lords, who had skin of stone.<br>Thrust the armament into the ground to create a gravity well.<br>In addition to dealing damage, this attack pulls enemies in.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>风暴刃</p><br>战技：风暴刃<br><br>史东薇尔的失传战技。<br>将武器缠绕风暴刃，朝前方释放风暴。<br>可以连续施放。</div><div class="t"><p>嵐の刃</p><br>戦技「嵐の刃」<br><br>ストームヴィルの失われた戦技<br>武器に嵐の刃を纏い、それを前方に放つ<br>連続で放つことができる<br></div><div class="t"><p>Storm Blade</p><br>Skill: Storm Blade<br><br>Lost skill of Stormveil.<br>Surround armament with shearing storm winds that can be fired forward.<br>Can be fired in rapid succession.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>撼地</p><br>战技：撼地<br><br>将武器刺入地面后，再向下使力<br>产生冲击波，引发剧烈摇晃的战技。<br>发动后接着使出重攻击，<br>能回旋横扫攻击。</div><div class="t"><p>地揺らし</p><br>戦技「地揺らし」<br><br>武器を地面に突き立てた後、力を込め<br>衝撃波と共に、大地を激しく揺らす戦技<br>強攻撃で、回転薙ぎ払いに繋げられる<br></div><div class="t"><p>Earthshaker</p><br>Skill: Earthshaker<br><br>Thrust armament into the ground, then gather strength to unleash an earth-shaking shockwave.<br>Follow up with a strong attack to swing the armament in a sweeping strike.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>黄金大地</p><br>战技：黄金大地<br><br>将武器刺入地面后，再向下使力<br>引发神圣爆炸，形成黄金石砾的战技。<br>发动后接着使出重攻击，<br>能回旋横扫攻击。</div><div class="t"><p>黄金の地</p><br>戦技「黄金の地」<br><br>武器を地面に突き立てた後、力を込め<br>聖なる爆発と共に、黄金のつぶてを生じる<br>強攻撃で、回転薙ぎ払いに繋げられる<br></div><div class="t"><p>Golden Land</p><br>Skill: Golden Land<br><br>Thrust armament into the ground, then gather strength to unleash a blast of sacred energy that coalesces into golden darts. Follow up with a strong attack to swing the armament in a sweeping strike.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>炎击</p><br>战技：炎击<br><br>朝前方大范围释放火焰的战技。<br>发动后接着使出重攻击，<br>能向前跨出、横扫攻击，并让武器缠绕火焰。</div><div class="t"><p>炎撃</p><br>戦技「炎撃」<br><br>前方広範囲に炎を放つ戦技<br>強攻撃で、踏み込む薙ぎ払いに繋げられる<br>またその時に、武器は炎を纏う<br></div><div class="t"><p>Flaming Strike</p><br>Skill: Flaming Strike<br><br>Skill that emits flame in a wide frontward arc.<br>Follow up with a strong attack to perform a lunging, sweeping strike.<br>This will also coat the armament in fire.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>落雷</p><br>战技：落雷<br><br>王城古龙信仰的战技之一。<br>武器指向天之后会蕴藏雷电，召唤落雷。<br>可以连续施放。</div><div class="t"><p>落雷</p><br>戦技「落雷」<br><br>王都古竜信仰の戦技のひとつ<br>突き上げる武器に雷を宿し、落雷を呼ぶ<br>連続で放つことができる<br></div><div class="t"><p>Thunderbolt</p><br>Skill: Thunderbolt<br><br>Skill used by the capital's ancient dragon cult.<br>Raise armament aloft to call down a bolt of lightning.<br>Can be fired in rapid succession.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>雷击斩</p><br>战技：雷击斩<br><br>让雷电打在武器上，再向下挥舞，<br>形成强力雷击的战技。<br>缠绕武器上的雷电会暂时延续。</div><div class="t"><p>雷撃斬</p><br>戦技「雷撃斬」<br><br>武器に雷を呼び、斬り下ろすことで<br>凄まじい雷撃を発生させる戦技<br>武器の雷は、しばらく継続する<br></div><div class="t"><p>Lightning Slash</p><br>Skill: Lightning Slash<br><br>Call down a bolt of lightning into armament, then swing it down to create an explosive shock.<br>The armament retains the lightning enchantment for a while.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>伟哉卡利亚</p><br>战技：伟哉卡利亚<br><br>喻为卡利亚王室象征的战技。<br>将剑身化为魔力大剑，再向下挥舞。<br>借由蓄力发动，能提升两个阶段。</div><div class="t"><p>グレート・カーリア</p><br>戦技「グレート・カーリア」<br><br>カーリア王家の象徴とされる戦技<br>剣身を魔力の大剣と化し、振り下ろす<br>タメ使用で、二段階に強化される<br></div><div class="t"><p>Carian Grandeur</p><br>Skill: Carian Grandeur<br><br>Carian royal prestige embodied in a skill.<br>Transform blade into a magical greatsword and swing it down.<br>Can be charged to increase its power by up to two levels.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>卡利亚大剑</p><br>战技：卡利亚大剑<br><br>喻为卡利亚王室象征的战技。<br>将剑身化为魔力大剑，再向下挥舞。<br>借由蓄力发动，能提升威力。</div><div class="t"><p>カーリアの大剣</p><br>戦技「カーリアの大剣」<br><br>カーリア王家の象徴とされる戦技<br>剣身を魔力の大剣と化し、振り下ろす<br>タメ使用で強化される<br></div><div class="t"><p>Carian Greatsword</p><br>Skill: Carian Greatsword<br><br>Carian royal prestige embodied in a skill.<br>Transform blade into a magical greatsword and swing it down.<br>Can be charged to increase its power.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>真空斩</p><br>战技：真空斩<br><br>古英雄们的失传战技。<br>高举剑身形成真空状态，<br>再化为真空刃，朝前方释放。</div><div class="t"><p>真空斬り</p><br>戦技「真空斬り」<br><br>古い英雄たちの失われた戦技<br>高く掲げた剣身に、真空を生じさせ<br>それを刃として前方に放つ<br></div><div class="t"><p>Vacuum Slice</p><br>Skill: Vacuum Slice<br><br>Lost skill of ancient heroes.<br>Hold the armament aloft to surround it with a shearing vacuum, then launch it forwards as a blade-like projectile.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>黑焰漩涡</p><br>战技：黑焰漩涡<br><br>旋转武器再刺向地面，<br>唤出漩涡状黑焰的战技。<br>持续发动的期间，<br>在旋转时也能形成黑焰漩涡。</div><div class="t"><p>黒炎の渦</p><br>戦技「黒炎の渦」<br><br>武器を回転させ、地面に突き刺し<br>渦巻く黒炎を呼ぶ戦技<br>長押しで、回転時も黒炎の渦が発生する<br></div><div class="t"><p>Black Flame Tornado</p><br>Skill: Black Flame Tornado<br><br>Spin armament overhead and then plunge it into the ground to summon a raging vortex of black flames.<br>Hold to create an initial flame tornado while spinning the armament.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>喷火</p><br>战技：喷火<br><br>吐出大口气吹向火把的火焰，<br>让火焰向前大范围燃烧的战技。<br>火焰会暂时在地面燃烧。</div><div class="t"><p>火吹き</p><br>戦技「火吹き」<br><br>松明の炎に激しく息を吹き付け<br>前方広範囲を焼き払う戦技<br>その炎は、少しの間、地面を燃やし続ける<br></div><div class="t"><p>Firebreather</p><br>Skill: Firebreather<br><br>Blow into torch flame, spreading flames in a wide frontward arc. The flames on the ground will continue to burn for a short time.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>幻影共击</p><br>战技：幻影共击<br><br>黑夜骑兵的恋旧战技。<br>能形成过去老师的幻影，一同突击上砍。<br>再次发动能使出追击。</div><div class="t"><p>共撃の幻</p><br>戦技「共撃の幻」<br><br>夜の騎兵の、郷愁の戦技<br>かつての師の幻影を生じ、共に突撃し斬り上げる<br>追加入力で追撃に繋げられる<br></div><div class="t"><p>Phantom Slash</p><br>Skill: Phantom Slash<br><br>Skill inspired by the fond remembrances of the Night's Cavalry. Creates an apparition of the knights' former instructor who guides a joint lunging upward swing. Additional input allows for a follow-up attack.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>幻影枪</p><br>战技：幻影枪<br><br>无头灵庙骑士使用的战技。<br>能形成幻影枪，投掷攻击。</div><div class="t"><p>幻影の槍</p><br>戦技「幻影の槍」<br><br>首のない霊廟騎士の戦技<br>幻影の槍を生じ、それを投擲する<br></div><div class="t"><p>Spectral Lance</p><br>Skill: Spectral Lance<br><br>Skill of the headless Mausoleum Knights.<br>Hurl a phantasmic spear at foes.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>寒气冻雾</p><br>战技：寒气冻雾<br><br>让武器缠绕寒气后使出斩击，<br>并在前方形成冻雾的战技。<br>缠绕武器上的寒气会暂时延续。</div><div class="t"><p>冷気の霧</p><br>戦技「冷気の霧」<br><br>武器に冷気を纏わせて斬り<br>前方に、その霧を生じる戦技<br>武器の冷気は、しばらく継続する<br></div><div class="t"><p>Chilling Mist</p><br>Skill: Chilling Mist<br><br>Coat armament in frost, and then slash, spreading frigid mist forwards.<br>The armament retains its frost for a while.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>盾牌冲击</p><br>战技：盾牌冲击<br><br>架稳盾牌、防御的同时，<br>利用全身的重量向前冲撞的战技。<br>对弱小的敌人使出，能让对方失去平衡。</div><div class="t"><p>シールドバッシュ</p><br>戦技「シールドバッシュ」<br><br>しっかりと盾を構え<br>ガードしたまま体重を乗せてぶつける戦技<br>非力な敵を押し出し、またよろめかせる<br></div><div class="t"><p>Shield Bash</p><br>Skill: Shield Bash<br><br>Brace behind shield before using bodyweight to ram foes while maintaining guarding stance.<br>Weaker enemies will be shoved backwards, and can even be staggered.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>铁壁盾防</p><br>战技：铁壁盾防<br><br>因骑士奈德哈特而闻名的战技。<br>将力量集中至盾牌，暂时强化盾牌的坚硬度，<br>能抵御更为强大的攻击。</div><div class="t"><p>鉄壁の盾</p><br>戦技「鉄壁の盾」<br><br>騎士ナイトハルトの名で知られる戦技<br>盾に力を集中させ、一時的に硬度を増し<br>より大きな攻撃を弾けるようにする<br></div><div class="t"><p>Barricade Shield</p><br>Skill: Barricade Shield<br><br>Skill made famous by Sir Neidhardt.<br>Focus your energy into the shield, temporarily hardening it to deflect greater blows.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>格挡</p><br>战技：格挡<br><br>拨开攻击的同时，让敌人失去平衡的战技。<br>需要在敌人近距离攻击时配合使用。<br>失去平衡后，使出“致命一击”的机会随之到来。</div><div class="t"><p>パリィ</p><br>戦技「パリィ」<br><br>近接攻撃にタイミングを合わせて使用し<br>攻撃を逸らし、敵の体勢を崩す戦技<br>致命の一撃のチャンスとなる<br></div><div class="t"><p>Parry</p><br>Skill: Parry<br><br>Use this skill in time with a foe's melee attack to deflect it and break that foe's stance.<br>This provides an opening to perform a critical hit.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>小圆盾格挡</p><br>战技：小圆盾格挡<br><br>拨开攻击的同时，让敌人失去平衡的战技。<br>需要在敌人近距离攻击时配合使用。<br>发动速度比战技“格挡”还快。</div><div class="t"><p>バックラーパリィ</p><br>戦技「バックラーパリィ」<br><br>近接攻撃にタイミングを合わせて使用し<br>攻撃を逸らし、敵の体勢を崩す戦技<br>通常のパリィよりも、速度に優れる<br></div><div class="t"><p>Buckler Parry</p><br>Skill: Buckler Parry<br><br>Use this skill in time with a foe's melee attack to deflect it and break that foe's stance.<br>This is faster than a regular parry.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>格挡</p><br>战技：格挡<br><br>拨开攻击的同时，让敌人失去平衡的战技。<br>需要在敌人近距离攻击时配合使用。<br>失去平衡后，使出“致命一击”的机会随之到来。</div><div class="t"><p>パリィ</p><br>戦技「パリィ」<br><br>近接攻撃にタイミングを合わせて使用し<br>攻撃を逸らし、敵の体勢を崩す戦技<br>致命の一撃のチャンスとなる<br></div><div class="t"><p>Parry</p><br>Skill: Parry<br><br>Use this skill in time with a foe's melee attack to deflect it and break that foe's stance.<br>This provides an opening to perform a critical hit.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>卡利亚式奉还</p><br>战技：卡利亚式奉还<br><br>挥动盾牌消除魔法、祷告的效用，<br>再用承受的力量化为浮空辉剑的战技。<br>也能发挥与战技“格挡”相同的功能。</div><div class="t"><p>カーリアの返報</p><br>戦技「カーリアの返報」<br><br>盾を払い、魔術や祈祷を消し去り<br>その力を輝剣として逆展開する戦技<br>また、通常のパリィとしても機能する<br></div><div class="t"><p>Carian Retaliation</p><br>Skill: Carian Retaliation<br><br>Swing the shield to dispel incoming sorceries and incantations, transforming the magic into retaliatory glintblades.<br>Can also be used in the same way as a regular parry.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>风暴障壁</p><br>战技：风暴障壁<br><br>挥动盾牌，在自身前方形成风暴障壁，<br>让箭之类的远攻道具偏移的战技。<br>也能发挥与战技“格挡”相同的功能。</div><div class="t"><p>嵐の壁</p><br>戦技「嵐の壁」<br><br>盾を払い、前方に嵐の壁を発生させ<br>矢などの飛び道具を逸らせる戦技<br>また、通常のパリィとしても機能する<br></div><div class="t"><p>Storm Wall</p><br>Skill: Storm Wall<br><br>Swing the shield to create a wall of storm winds in front of you, deflecting arrows and other such physical projectiles.<br>Can also be used in the same way as a regular parry.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黄金格挡</p><br>战技：黄金格挡<br><br>执行黄金树祷告的同时挥动盾牌，<br>让敌人的攻击偏移，并失去平衡的战技。<br>与敌人有些距离也能产生效用。</div><div class="t"><p>黄金パリィ</p><br>戦技「黄金パリィ」<br><br>黄金樹の祈祷と共に、盾を払い<br>敵の攻撃を逸らし、体勢を崩す戦技<br>少し離れた距離でも有効となる<br></div><div class="t"><p>Golden Parry</p><br>Skill: Golden Parry<br><br>Perform an Erdtree incantation and swing the shield to deflect enemy attacks and break their stance.<br>Effective even at a slight distance.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>突进冲击</p><br>战技：突进冲击<br><br>用双手共持盾牌，<br>防御的同时，向前突进的战技。<br>对弱小的敌人使出，能让对方失去平衡。<br>持续发动能增加移动距离。</div><div class="t"><p>突撃バッシュ</p><br>戦技「突撃バッシュ」<br><br>両手で盾を構え、ガードしたまま突撃する戦技<br>非力な敵を押し出し、またよろめかせる<br>長押しで前進距離を伸ばすことができる<br></div><div class="t"><p>Shield Crash</p><br>Skill: Shield Crash<br><br>Two-hand the shield and charge forwards while maintaining guard. Weaker enemies will be shoved backwards and can even be staggered.<br>Hold to extend the duration of the charge forwards.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>托普斯的力场</p><br>战技：托普斯的力场<br><br>张开魔力力场的同时挥动盾牌，<br>能拨开魔法、祷告的战技。<br>也能发挥与战技“格挡”相同的功能。</div><div class="t"><p>トープスの力場</p><br>戦技「トープスの力場」<br><br>魔力の力場と共に、盾を払い<br>魔術や祈祷を逸らす戦技<br>また、通常のパリィとしても機能する<br></div><div class="t"><p>Thops's Barrier</p><br>Skill: Thops's Barrier<br><br>Erect a magical forcefield while swinging the shield to deflect sorceries and incantations.<br>Can also be used in the same way as a regular parry.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>贯穿射击</p><br>战技：贯穿射击<br><br>能侧身拉开大弓，强大的射手战技。<br>拉开大弓的同时也扭转弓弦，<br>增加大箭的旋转度，借此贯穿敌人的身体。</div><div class="t"><p>貫通射撃</p><br>戦技「貫通射撃」<br><br>大弓を半身に構える、剛力の射手の戦技<br>構えながら、大矢を捻り射ることで<br>それは、敵の体を貫通する<br></div><div class="t"><p>Through and Through</p><br>Skill: Through and Through<br><br>Powerful archery skill using a greatbow held in an oblique stance.<br>Ready the greatbow, then twist the bowstring to fire a mighty greatarrow that can penetrate through enemies.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>连续射击</p><br>战技：连续射击<br><br>能水平拉弓的射手战技。<br>摆出架式后，能以肉眼难以追上的速度，<br>连续射出箭。</div><div class="t"><p>連続射撃</p><br>戦技「連続射撃」<br><br>水平に弓を構える、射手の戦技<br>構えながら、目にも止まらぬ速さで<br>連続で矢を射ることができる<br></div><div class="t"><p>Barrage</p><br>Skill: Barrage<br><br>Archery skill using a bow held horizontally.<br>Ready the bow, then fire off a rapid succession of shots faster than the eye can see.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>拉满弓</p><br>战技：拉满弓<br><br>能侧身拉弓的射手战技。<br>摆出架式后，用力拉满弓，<br>能提升箭的攻击威力，突破敌人防御。</div><div class="t"><p>強射</p><br>戦技「強射」<br><br>半身に弓を構える、射手の戦技<br>構えながら、引き絞って射ることで<br>その矢は威力を増し、ガードを貫く<br></div><div class="t"><p>Mighty Shot</p><br>Skill: Mighty Shot<br><br>Archery skill performed from an oblique stance.<br>Ready the bow, then pull the bowstring to its limit to enhance the power of the shot, penetrating the enemy's guard.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>宿灵射击</p><br>战技：宿灵射击<br><br>摆出架式，让灵魂寄宿在箭之上，<br>再射击的战技。飞行速度比一般的箭更快。<br>仿佛会追踪目标，飞行轨道会随之调整。</div><div class="t"><p>宿し撃ち</p><br>戦技「宿し撃ち」<br><br>弓を構え、矢に霊を宿して射る戦技<br>その矢は、通常よりも速く飛び<br>目標を追うように、その軌道を変える<br></div><div class="t"><p>Enchanted Shot</p><br>Skill: Enchanted Shot<br><br>Archery skill that enlivens the arrow with spiritual essence.<br>The resulting shot will fly faster than regular shots and change its trajectory to follow the target.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>对空射击</p><br>战技：对空射击<br><br>压低身形拉弓的射手战技。<br>摆出架式后，朝天空射出箭，<br>箭会从敌人上方落下。</div><div class="t"><p>空撃ち</p><br>戦技「空撃ち」<br><br>低い姿勢で弓を構える、射手の戦技<br>構えながら、空に向かい矢を射る<br>その矢は、敵の頭上に降ってくる<br></div><div class="t"><p>Sky Shot</p><br>Skill: Sky Shot<br><br>Archery skill performed from a low stance.<br>Ready the bow, then fire an arrow high up into the air, arcing so as to strike the enemy from above when it comes down.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>箭雨</p><br>战技：箭雨<br><br>压低身形拉弓的战技。<br>摆出架式后，朝天空一口气射出多支箭，<br>箭会如雨一般，从敌人上方倾注而下。</div><div class="t"><p>アローレイン</p><br>戦技「アローレイン」<br><br>低い姿勢で弓を構える戦技<br>構えながら、複数の矢を一気に空に射る<br>それは、雨のごとく敵に降り注ぐ<br></div><div class="t"><p>Rain of Arrows</p><br>Skill: Rain of Arrows<br><br>Archery skill performed from a low stance.<br>Ready the bow, then fire a burst of arrows into the sky to shower the enemy with projectiles.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>冻霜踏地</p><br>战技：冻霜踏地<br><br>大力踏向地面，让冻霜随之扩散的战技。<br>冻霜会引发异常状态冻伤。</div><div class="t"><p>霜踏み</p><br>戦技「霜踏み」<br><br>大地を強く踏み、霜の地走りを起こす戦技<br>霜には、冷気の状態異常効果がある<br></div><div class="t"><p>Hoarfrost Stomp</p><br>Skill: Hoarfrost Stomp<br><br>Stomp hard to spread a trail of freezing mist on the ground.<br>The mist applies the frost status effect.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>风暴足</p><br>战技：风暴足<br><br>史东薇尔的风暴战技之一。<br>能大力踏向地面，在自身周围引发瞬间的风暴。</div><div class="t"><p>嵐脚</p><br>戦技「嵐脚」<br><br>ストームヴィルの嵐の戦技のひとつ<br>大地を強く踏み、自らの周りに一瞬の嵐を起こす<br></div><div class="t"><p>Storm Stomp</p><br>Skill: Storm Stomp<br><br>One of the skills that channel the tempests of Stormveil.<br>Stomp hard on the ground to kick up a momentary storm.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>踢击</p><br>战技：踢击<br><br>大幅抬起脚向前踢的战技。<br>对正在防御的敌人很有效，能使对方失去平衡。<br>朴实却又实用的战技。</div><div class="t"><p>キック</p><br>戦技「キック」<br><br>脚を大きく上げ、蹴りつける戦技<br>ガードに対し有効で、体勢を崩すことができる<br>単純だが実戦的な戦技<br></div><div class="t"><p>Kick</p><br>Skill: Kick<br><br>Push an enemy back with a high kick.<br>Effective against enemies who are guarding, and can break a foe's stance.<br>Sometimes a simple tool is the most effective.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>红狮子火焰</p><br>战技：红狮子火焰<br><br>与拉塔恩将军并肩作战的<br>红狮子军队所使用的战技。<br>能朝前方释放大范围的强烈火焰。</div><div class="t"><p>赤獅子の炎</p><br>戦技「赤獅子の炎」<br><br>将軍ラダーンと共に戦った、赤獅子の軍勢の戦技<br>前方広範囲に、強い炎を放つ<br></div><div class="t"><p>Flame of the Redmanes</p><br>Skill: Flame of the Redmanes<br><br>Skill of the Redmanes, who fought alongside General Radahn.<br>Produce a powerful burst of flames in a wide frontward arc.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>坠落震击</p><br>战技：坠落震击<br><br>轻盈向前跳，再顺势用臀部<br>用力向下坠落的战技。<br>此攻击能引发剧烈的冲击波。</div><div class="t"><p>ヒップドロップ</p><br>戦技「ヒップドロップ」<br><br>ふわりと前方に跳躍し<br>そのまま、重い尻を落としていく戦技<br>その尻撃は、激しい衝撃波を発生させる<br></div><div class="t"><p>Ground Slam</p><br>Skill: Ground Slam<br><br>Jump up high into the air and crash down on the ground ahead.<br>The resulting pratfall sends a powerful shockwave in all directions.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黄金坠落震击</p><br>战技：黄金坠落震击<br><br>守护小黄金树的化身使用的战技。<br>能轻盈向前跳，用臀部用力向下坠落，<br>此攻击能引发黄金冲击波。</div><div class="t"><p>黄金の尻撃</p><br>戦技「黄金の尻撃」<br><br>小黄金樹を守る、化身の戦技<br>ふわりと前方に跳躍し、重い尻を落とす<br>その尻撃は、黄金の衝撃波を発生させる<br></div><div class="t"><p>Golden Slam</p><br>Skill: Golden Slam<br><br>Skill of the avatars who protect Minor Erdtrees.<br>Jump up high into the air and crash down on the ground ahead.<br>The resulting pratfall sends golden shockwaves in all directions.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黑暗波动</p><br>战技：黑暗波动<br><br>将武器刺入地面后，在自身周围<br>产生三道黑暗波动的战技。<br>发动后接着使出重攻击，能回旋横扫攻击。</div><div class="t"><p>暗黒波</p><br>戦技「暗黒波」<br><br>武器を地面に突き立て、自らの周りに<br>三度の暗黒波を発生させる戦技<br>強攻撃で、回転薙ぎ払いに繋げられる<br></div><div class="t"><p>Waves of Darkness</p><br>Skill: Waves of Darkness<br><br>Plunge armament into the ground to release three waves of darkness.<br>Follow up with a strong attack to swing the armament in a sweeping strike.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>荷莱·露的撼地</p><br>战技：荷莱·露的撼地<br><br>以张开的双臂敲向地面，<br>产生冲击波，引发剧烈摇晃的战技。<br>再次发动能再一次敲击地面。</div><div class="t"><p>ホーラ・ルーの地揺らし</p><br>戦技「ホーラ・ルーの地揺らし」<br><br>広げた両手で地面を叩き<br>衝撃波と共に、大地を激しく揺らす戦技<br>追加入力で、もう一度地面を叩く<br></div><div class="t"><p>Hoarah Loux's Earthshaker</p><br>Skill: Hoarah Loux's Earthshaker<br><br>Slam both hands onto the ground to violently shake the earth and unleash a shockwave.<br>Follow up with an additional input to slam the ground again.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>决心</p><br>战技：决心<br><br>骑士们的战技。<br>将武器移向眼前、指向天空，坚定决心，<br>提升下一记攻击的威力。</div><div class="t"><p>デターミネーション</p><br>戦技「デターミネーション」<br><br>騎士たちの戦技<br>武器を眼前に掲げ、決意を誓い<br>次の一撃の威力を高める<br></div><div class="t"><p>Determination</p><br>Skill: Determination<br><br>A knightly skill.<br>Hold the flat of the armament to your face and pledge your resolve, powering up your next attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>侍王骑士的决心</p><br>战技：侍王骑士的决心<br><br>过去侍奉艾尔登之王的骑士们使用的战技。<br>将武器移向眼前、指向天空，坚定决心，<br>大幅提升下一记攻击的威力。</div><div class="t"><p>王騎士の決意</p><br>戦技「王騎士の決意」<br><br>かつてエルデの王に仕えた、騎士たちの戦技<br>武器を眼前に掲げ、決意を誓い<br>次の一撃の威力を大きく高める<br></div><div class="t"><p>Royal Knight's Resolve</p><br>Skill: Royal Knight's Resolve<br><br>Skill of the knights who once served the Elden Lord.<br>Hold the flat of the armament to your face and pledge your resolve, greatly powering up your next attack.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>暗杀办法</p><br>战技：暗杀办法<br><br>自伤之后，消除自身存在的战技。<br>能让施放者的身影难以辨认，<br>也能消除施放者的脚步声。</div><div class="t"><p>暗殺の作法</p><br>戦技「暗殺の作法」<br><br>自らを傷付け、その存在を消す戦技<br>使用者の姿は視認し難くなり<br>またその足音も消える<br></div><div class="t"><p>Assassin's Gambit</p><br>Skill: Assassin's Gambit<br><br>Skill that masks the user's presence at the cost of a self-inflicted wound.<br>Grants near-invisibility and silences footsteps.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>黄金树立誓</p><br>战技：黄金树立誓<br><br>王城骑士们自古继承而来的战技。<br>将武器指向天空，发誓为黄金树而战，<br>提升自己与周围我方人物的攻击力与防御力。</div><div class="t"><p>黄金樹に誓って</p><br>戦技「黄金樹に誓って」<br><br>王都の騎士たちに、古くから伝わる戦技<br>武器を掲げ、黄金樹に戦いを誓い<br>自らと周囲の味方の、攻撃力と防御力を高める<br></div><div class="t"><p>Golden Vow</p><br>Skill: Golden Vow<br><br>Skill passed down from antiquity among the knights of the capital. Raise armament aloft and pledge to honor the Erdtree in battle, granting self and nearby allies increased attack power and defense.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>圣律</p><br>战技：圣律<br><br>黄金律法基本主义者的骑士们使用的战技。<br>敬礼的同时，能替武器附加神圣性。<br>对死诞者的伤害尤为巨大。</div><div class="t"><p>聖律</p><br>戦技「聖律」<br><br>黄金律原理主義の騎士たちの戦技<br>敬礼と共に、武器に聖性を付与する<br>特に、死に生きる者たちに効果が高い<br></div><div class="t"><p>Sacred Order</p><br>Skill: Sacred Order<br><br>Skill of the Golden Order fundamentalist knights.<br>Perform a salute and grant the armament holy essence.<br>Highly effective against Those Who Live in Death.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>共享圣律</p><br>战技：共享圣律<br><br>黄金律法基本主义者的骑士们使用的战技。<br>能替自身与周围我方人物的武器附加神圣性。<br>对死诞者的伤害尤为巨大。</div><div class="t"><p>聖律共有</p><br>戦技「聖律共有」<br><br>黄金律原理主義の騎士たちの戦技<br>自らと周囲の味方の武器に、聖性を付与する<br>特に、死に生きる者たちに効果が高い<br></div><div class="t"><p>Shared Order</p><br>Skill: Shared Order<br><br>Skill of the Golden Order fundamentalist knights.<br>Grant the armament and those of nearby allies holy essence.<br>Highly effective against Those Who Live in Death.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>切腹</p><br>战技：切腹<br><br>芦苇之地的剑客，禁用的奥义。<br>将武器深深刺入自己的腹部，染上鲜血，<br>能提升攻击力、强化异常状态出血的效果。</div><div class="t"><p>切腹</p><br>戦技「切腹」<br><br>葦の地の剣客の、禁じられた奥義<br>自らの腹を深く刺し、刃を血で染め<br>攻撃力と、出血の状態異常効果を高める<br></div><div class="t"><p>Seppuku</p><br>Skill: Seppuku<br><br>A forbidden technique used by swordsmen from the Land of Reeds. Plunge the blade into your stomach to stain it with blood. Increases attack power and improves ability to inflict blood loss.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>岩石剑</p><br>战技：岩石剑<br><br>以重力招式为人知晓的战技。<br>将武器敲向地面，让岩石攀附其上。<br>能提升攻击力，也容易让敌人失去平衡。</div><div class="t"><p>岩石剣</p><br>戦技「岩石剣」<br><br>重力の技として知られる戦技<br>武器を地面に叩きつけ、岩石を纏わせる<br>攻撃力が高まり、また敵の体勢を崩しやすい<br></div><div class="t"><p>Cragblade</p><br>Skill: Cragblade<br><br>Skill that manipulates gravity.<br>Bury the armament in the ground, pulling rocks from the earth to reinforce it. Increases attack power and makes it easier to break enemy stance.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>野蛮咆哮</p><br>战技：野蛮咆哮<br><br>发出野兽般的咆哮，<br>借此激励自己，提升攻击力的战技。<br>在战技有效期间内，重攻击会变成野蛮连击。</div><div class="t"><p>野蛮な咆哮</p><br>戦技「野蛮な咆哮」<br><br>獣じみた咆哮を上げ<br>自らを鼓舞し、攻撃力を高める戦技<br>効果中、強攻撃が野蛮な連撃となる<br></div><div class="t"><p>Barbaric Roar</p><br>Skill: Barbaric Roar<br><br>Let loose a bestial roar to rally the spirit and increase attack power.<br>While active, strong attacks change to savage combo attacks.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>战吼</p><br>战技：战吼<br><br>透过咆哮激励自己，提升攻击力的战技。<br>在战技有效期间内，重攻击会变成突进攻击。</div><div class="t"><p>ウォークライ</p><br>戦技「ウォークライ」<br><br>咆哮により自らを鼓舞し、攻撃力を高める戦技<br>効果中、強攻撃が突進攻撃となる<br></div><div class="t"><p>War Cry</p><br>Skill: War Cry<br><br>Give a war cry to rally the spirit and increase attack power.<br>While active, strong attacks change to charging attacks.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>野兽咆哮</p><br>战技：野兽咆哮<br><br>发出野兽般的咆哮，划破空气，<br>将咆哮声化成球体释放的战技。</div><div class="t"><p>獣の咆哮</p><br>戦技「獣の咆哮」<br><br>獣じみた咆哮を上げ、空気を切り裂き<br>それを弾丸として前方に放つ戦技<br></div><div class="t"><p>Beast's Roar</p><br>Skill: Beast's Roar<br><br>Unleash a beastly roar, rending the air as a forward-travelling projectile.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>山妖咆哮</p><br>战技：山妖咆哮<br><br>望向远方发出咆哮，<br>能弹飞周围人物，产生冲击波。<br>发动后接着使出重攻击，能激烈敲击。</div><div class="t"><p>トロルの咆哮</p><br>戦技「トロルの咆哮」<br><br>彼方を見上げて咆哮し<br>周囲を吹き飛ばす、衝撃波を発生させる<br>また、強攻撃で激しい叩きつけに繋げられる<br></div><div class="t"><p>Troll's Roar</p><br>Skill: Troll's Roar<br><br>Look into the distance and let out an intense roar, generating a powerful shockwave that blows back surrounding foes.<br>Follow up with a strong attack to slam the armament down.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>夸耀咆哮</p><br>战技：夸耀咆哮<br><br>犹如夸耀自我般发出咆哮，<br>能提升攻击力、防御力、精力恢复速度的战技。</div><div class="t"><p>誇示する咆哮</p><br>戦技「誇示する咆哮」<br><br>自らを誇示するように咆哮し<br>攻撃力、防御力、スタミナ回復速度を高める戦技<br></div><div class="t"><p>Braggart's Roar</p><br>Skill: Braggart's Roar<br><br>Declare your presence with a boastful roar.<br>Raises attack power, defense, and stamina recovery speed.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>忍耐</p><br>战技：忍耐<br><br>心中做好准备放低重心，站稳步伐，<br>能瞬间提升强韧度的战技。<br>在战技有效期间内，能减轻受到的损伤。</div><div class="t"><p>我慢</p><br>戦技「我慢」<br><br>覚悟と共に腰を落とし踏ん張り<br>瞬間的に、強靭度を高める戦技<br>我慢中は被ダメージも軽減される<br></div><div class="t"><p>Endure</p><br>Skill: Endure<br><br>Assume an anchored stance to brace for incoming attacks, briefly boosting poise.<br>Damage taken while using this skill is reduced.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>无敌</p><br>战技：无敌<br><br>黄金树的古老战士们使用的战技。<br>高举盾牌，让黄金力量充满全身，<br>能够瞬间呈现无敌状态。</div><div class="t"><p>無敵</p><br>戦技「無敵」<br><br>黄金樹の古い戦士たちの戦技<br>盾を掲げ、黄金の力を身体に纏い<br>瞬間的に無敵になる<br></div><div class="t"><p>Vow of the Indomitable</p><br>Skill: Vow of the Indomitable<br><br>Skill of the ancient warriors of the Erdtree.<br>Hold shield aloft to imbue yourself with golden power, granting momentary invincibility.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>圣域</p><br>战技：圣域<br><br>高举盾牌，展开黄金树圣域的战技。<br>能持续恢复血量，提升防御力，<br>圣域内的我方人物也能蒙受相同效果。</div><div class="t"><p>聖域</p><br>戦技「聖域」<br><br>盾を掲げ、黄金樹の聖域を展開する戦技<br>ＨＰを持続的に回復し、防御力も高める<br>聖域内の味方にも同様の効果がある<br></div><div class="t"><p>Holy Ground</p><br>Skill: Holy Ground<br><br>Raise shield to create an Erdtree-consecrated area that continuously restores HP and boosts defense for self and allies inside it.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>碎步</p><br>战技：碎步<br><br>以速度干扰敌人的战斗者们使用的战技。<br>能以轻盈步伐快速移动。<br>在锁定目标的状态下使用，能以目标为中心移动。</div><div class="t"><p>クイックステップ</p><br>戦技「クイックステップ」<br><br>機敏さと攪乱で戦う者たちの戦技<br>素早くステップ移動する<br>ターゲット固定状態では、回り込みとなる<br></div><div class="t"><p>Quickstep</p><br>Skill: Quickstep<br><br>Skill prized by the crafty and fleet of foot.<br>Perform a quickstep maneuver that allows for circling around lock-on targets.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>猎犬步法</p><br>战技：猎犬步法<br><br>能瞬间消失身影，以踏步移动的战技。<br>移动速度快，距离也长。<br>在锁定目标的状态下使用，能以目标为中心移动。</div><div class="t"><p>猟犬のステップ</p><br>戦技「猟犬のステップ」<br><br>一瞬に姿を消し、ステップ移動する戦技<br>それは高速で、また移動距離も長い<br>ターゲット固定状態では、回り込みとなる<br></div><div class="t"><p>Bloodhound's Step</p><br>Skill: Bloodhound's Step<br><br>Skill that allows the user to become temporarily invisible while dodging at high speed. Moves faster and travels farther than a regular quickstep.<br>This skill can be used to circle around lock-on targets.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>潜雾猛禽</p><br>战技：潜雾猛禽<br><br>压低身形，瞬间消失身影的战技。<br>受到攻击时能长出猛禽翅膀，<br>瞬间一跃而起。</div><div class="t"><p>霧の猛禽</p><br>戦技「霧の猛禽」<br><br>体を沈め、瞬間的に姿を消す戦技<br>攻撃を受けると、猛禽の羽を生じ<br>一瞬に空に飛ぶ<br></div><div class="t"><p>Raptor of the Mists</p><br>Skill: Raptor of the Mists<br><br>Duck into a low stance, momentarily vanishing.<br>If an enemy attack connects, avian wings will allow for a quick escape into the air.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p>白影诱惑</p><br>战技：白影诱惑<br><br>对着武器发愿，在自身前方形成白色影子。<br>能吸引非战斗状态，为人类之身的敌人注意，<br>引诱对方攻击的战技。但对上亚人时，<br>即使对方在战斗状态，也具有诱敌效用。</div><div class="t"><p>白い影の誘い</p><br>戦技「白い影の誘い」<br><br>武器に念じ、前方に白い影を生じ<br>戦闘状態にない人の類を引き寄せ、攻撃を誘う戦技<br>亜人に対しては、戦闘状態であっても効果がある<br></div><div class="t"><p>White Shadow's Lure</p><br>Skill: White Shadow's Lure<br><br>Hold armament in a brief, silent prayer to create a white shadow.<br>The apparition lures in foes of human build who are not in combat, drawing their aggression. Effective on demi-humans even if they are already in a combat state.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>信仰喷发</p><br>专用战技：信仰喷发<br><br>在尊容火杯里，燃烧彼拉克的信仰火焰，<br>再将火杯向上突刺，喷发大量火焰的战技。<br>再次发动能多次向上突刺。</div><div class="t"><p>噴き上がる信仰</p><br>専用戦技「噴き上がる信仰」<br><br>尊顔の盃に、ビラクの信仰の炎を燃やし<br>それを突き上げ、大量の火を噴き上げる戦技<br>追加入力で、何度でも突き上げる<br></div><div class="t"><p>Surge of Faith</p><br>Unique Skill: Surge of Faith<br><br>Set the flames of Birac's faith ablaze in the cranial vessel, then raise it aloft to rain down fireballs in all directions.<br>Repeated inputs will continue to raise the armament aloft, continuing the attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>神谕泡泡</p><br>专用战技：神谕泡泡<br><br>吹奏笛子，释放魔力泡泡的战技。<br>泡泡会缓缓飘动，并朝目标飞去。</div><div class="t"><p>神託のシャボン</p><br>専用戦技「神託のシャボン」<br><br>笛を吹き、魔力のシャボンを放つ戦技<br>シャボンはゆっくりと飛びながら<br>目標にふわふわと向かっていく<br></div><div class="t"><p>Oracular Bubble</p><br>Unique Skill: Oracular Bubble<br><br>Blow on the horn to release a magic bubble.<br>The bubble floats gently through the air towards its target.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>倾注泡泡</p><br>专用战技：倾注泡泡<br><br>吹奏笛子，释放大量魔力泡泡的战技。<br>泡泡会缓缓飘动，并朝目标倾注而下。</div><div class="t"><p>降り注ぐシャボン</p><br>専用戦技「降り注ぐシャボン」<br><br>笛を吹き、魔力のシャボンを大量に放つ戦技<br>シャボンはゆっくりと飛びながら、降り注ぐ<br></div><div class="t"><p>Bubble Shower</p><br>Unique Skill: Bubble Shower<br><br>Blow on the horn to release a spume of magic bubbles.<br>The bubbles float gently before raining down on the target.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>神谕大泡泡</p><br>专用战技：神谕大泡泡<br><br>吹奏笛子，释放魔力大泡泡的战技。<br>大泡泡会缓缓飘动，并朝目标飞去。</div><div class="t"><p>神託の大シャボン</p><br>専用戦技「神託の大シャボン」<br><br>笛を吹き、魔力の大シャボンを放つ戦技<br>大シャボンはゆっくりと飛びながら<br>目標にふわふわと向かっていく<br></div><div class="t"><p>Great Oracular Bubble</p><br>Unique Skill: Great Oracular Bubble<br><br>Blow on the horn to release a massive magic bubble.<br>The bubble floats gently through the air towards its target.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>熔岩海</p><br>专用战技：熔岩海<br><br>能大幅挥动熔岩鞭子，<br>暂时在自身周围形成熔岩海的战技。<br>持续发动的时间，能持续挥舞熔岩鞭子。</div><div class="t"><p>溶岩の海</p><br>専用戦技「溶岩の海」<br><br>溶岩の鞭を大きく振り回し<br>一時、自分の周りに溶岩の海を生じる戦技<br>長押ししている間、鞭を振り回し続ける<br></div><div class="t"><p>Sea of Magma</p><br>Unique Skill: Sea of Magma<br><br>Swing a molten whip overhead to temporarily cover the surrounding area in a sea of magma.<br>Hold to continue swinging the lava whip.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>月光剑</p><br>专用战技：月光剑<br><br>高举剑，让整把剑发出暗月月光的战技。<br>能暂时提升魔力属性攻击力，<br>让剑身缠绕冻伤寒气。<br>蓄力攻击能释放月光波。</div><div class="t"><p>月光剣</p><br>専用戦技「月光剣」<br><br>剣を掲げ、暗月の月光を輝かせる戦技<br>魔力攻撃力を一時的に高め、剣身に冷気を纏う<br>また、タメ攻撃で月光の光波を放つ<br></div><div class="t"><p>Moonlight Greatsword</p><br>Unique Skill: Moonlight Greatsword<br><br>Raise the sword aloft, bathing it in the light of the dark moon.<br>Temporarily increases magic attack power and imbues blade with frost.<br>Charged attacks release blasts of moonlight.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>志留亚的漩涡</p><br>专用战技：志留亚的漩涡<br><br>旋转树矛、缠绕风流漩涡，再使出突刺的战技。<br>借由蓄力发动，会变得具有弹飞敌人的威力，<br>也能朝前方释放风流漩涡。</div><div class="t"><p>シルリアの渦</p><br>専用戦技「シルリアの渦」<br><br>樹槍を回転させ、風の渦を纏って突き出す戦技<br>タメ使用で、敵を吹き飛ばす威力を持ち<br>また、風の渦を前方に放つことができる<br></div><div class="t"><p>Siluria's Woe</p><br>Unique Skill: Siluria's Woe<br><br>Thrust the weapon in a spiraling motion, surrounding it in a vortex of wind.<br>Charged attacks have the power to blow away enemies and can fire the tornado forwards.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>归于麾下</p><br>专用战技：归于麾下<br><br>高举军旗，以勇猛姿态发出号令的战技。<br>能提升自身与周围我方人物的攻击力、防御力。</div><div class="t"><p>軍旗の下に</p><br>専用戦技「軍旗の下に」<br><br>軍旗を掲げ、勇ましく号令をかける戦技<br>自らと周囲の味方の、攻撃力と防御力を高める<br></div><div class="t"><p>Rallying Standard</p><br>Unique Skill: Rallying Standard<br><br>Hoist the war banner aloft and give a rallying command.<br>Raises attack power and defense for self and nearby allies.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>敬请见证！</p><br>专用战技：敬请见证！<br><br>暂时赋予小型龙生命，高举指向天空，<br>朝前方大范围落下龙焰的战技。</div><div class="t"><p>ご照覧あれい！</p><br>専用戦技「ご照覧あれい！」<br><br>小さな竜に、一時の生命を与え<br>それを天に突き上げることで<br>竜の炎を、前方広範囲に降らせる戦技<br></div><div class="t"><p>Bear Witness!</p><br>Unique Skill: Bear Witness!<br><br>Grant the small dragon a fleeting glimpse of life and thrust it skyward, spewing flames over a wide frontward area.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>欧赫剑舞</p><br>专用战技：欧赫剑舞<br><br>把气灌入剑中，旋转之后朝前方释放的战技。<br>整把剑会剧烈旋转，给予连续伤害。<br>借由蓄力发动，能提升飞翔距离与旋转时间。</div><div class="t"><p>エオヒドの剣舞</p><br>専用戦技「エオヒドの剣舞」<br><br>剣に気を宿し、捻りを加え前方に放つ戦技<br>その剣は激しく回転し、連続でダメージを与える<br>タメ使用で飛距離を増し、回転の持続時間も増す<br></div><div class="t"><p>Eochaid's Dancing Blade</p><br>Unique Skill: Eochaid's Dancing Blade<br><br>Infuse the sword with energy, then fling it forwards in a corkscrew attack. The sword continuously deals damage while violently spinning.<br>Charge the attack to increase reach and duration of the spin.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>恶意气息</p><br>专用战技：恶意气息<br><br>高举展翼大角，招来恶意气息的战技。<br>能暂时降低周围敌人的防御力。</div><div class="t"><p>霊障招き</p><br>専用戦技「霊障招き」<br><br>大角の翼を掲げ、霊障を招く戦技<br>周囲の敵の防御力を一時的に低下させる<br></div><div class="t"><p>Soul Stifler</p><br>Unique Skill: Soul Stifler<br><br>Raise the greathorn's wings to summon a soul-sapping miasma.<br>Enemies in the affected area will temporarily suffer from reduced defense.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>掠夺火焰</p><br>专用战技：掠夺火焰<br><br>高举圣剑，燃起亵渎火焰，<br>再朝前方释放烈火的战技。<br>火焰会夺取血量。</div><div class="t"><p>略奪の炎</p><br>専用戦技「略奪の炎」<br><br>聖剣を掲げ、冒涜の炎を燃やし<br>激しく前方に放つ戦技<br>その炎は、ＨＰを奪う<br></div><div class="t"><p>Taker's Flames</p><br>Unique Skill: Taker's Flames<br><br>Raise the sacred sword aloft to set it ablaze with blasphemous flames, then bring it down to fire off a forward blast.<br>The flames steal HP from those they touch.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>灭洛斯的狂嚎</p><br>专用战技：灭洛斯的狂嚎<br><br>发出带有诅咒的恐怖狂嚎，<br>让周围的敌人降低所有属性的减伤率、<br>所有异常状态的抵抗力。<br>在战技有效期间内，重攻击会变成连击。</div><div class="t"><p>ミエロスの絶叫</p><br>専用戦技「ミエロスの絶叫」<br><br>呪われた、おぞましい絶叫を上げ<br>周囲の敵の、すべての属性カット率と<br>すべての状態異常耐性を低下させる戦技<br>また効果中、強攻撃が連撃となる<br></div><div class="t"><p>Shriek of Milos</p><br>Unique Skill: Shriek of Milos<br><br>Lets out a horrific cursed scream that reduces all damage negation and status resistances for nearby foes.<br>While active, strong attacks will change to a combo attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>逆刺血刃</p><br>专用战技：逆刺血刃<br><br>将锯齿状剑刃上的湿漉鲜血，<br>化为引发出血的刀刃，释放而出的战技。<br>可以连续施放。</div><div class="t"><p>レドゥビアの血刃</p><br>専用戦技「レドゥビアの血刃」<br><br>ぎざ刃の乾かぬ血濡れを<br>出血を強いる刃となし放つ戦技<br>連続で放つことができる<br></div><div class="t"><p>Reduvia Blood Blade</p><br>Unique Skill: Reduvia Blood Blade<br><br>Slash with the wicked dagger, transforming its never-drying bloodstains into airborne blades that cause blood loss.<br>Can be fired in rapid succession.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>辉石彗砾</p><br>专用战技：辉石彗砾<br><br>能施展魔法“辉石魔砾”的战技。<br>借由蓄力发动，能变成“辉石彗砾”。<br>发动后接着使出重攻击，<br>能大幅向前跨出，再突刺攻击，</div><div class="t"><p>輝石の彗礫</p><br>専用戦技「輝石の彗礫」<br><br>「輝石のつぶて」の魔術を用いる戦技<br>タメ使用で、それは「輝石の彗礫」となる<br>また強攻撃で、大きく踏み込む突きに繋げられる<br></div><div class="t"><p>Glintstone Dart</p><br>Unique Skill: Glintstone Dart<br><br>Skill that builds from the Glintstone Pebble sorcery.<br>Charge the skill to upgrade it to Glintstone Dart.<br>Follow up with a strong attack to chain this skill into a lunging thrust.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>流体化</p><br>专用战技：流体化<br><br>让武器暂时化为流体的战技。<br>能像软鞭般挥动，大范围横扫敌人。</div><div class="t"><p>流体化</p><br>専用戦技「流体化」<br><br>武器を一時的に流体となす戦技<br>鞭のように振るい、広範囲を斬り払う<br></div><div class="t"><p>Flowing Form</p><br>Unique Skill: Flowing Form<br><br>Temporarily transforms armament into its liquid form.<br>Swing the armament like a whip to perform a sweeping slice over a wide area.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>夜与火的架式</p><br>专用战技：夜与火的架式<br><br>举起剑与地面平行，接着施展魔法的战技。<br>轻攻击能将魔力化为“黑夜彗星”释放；<br>重攻击能用火焰大范围横扫前方。</div><div class="t"><p>夜と炎の構え</p><br>専用戦技「夜と炎の構え」<br><br>剣を水平に構え、魔術に繋げる戦技<br>通常攻撃で、魔力を夜の彗星として放ち<br>強攻撃で、前方広範囲を炎で薙ぎ払う<br></div><div class="t"><p>Night-and-Flame Stance</p><br>Unique Skill: Night-and-Flame Stance<br><br>Hold the sword level and prepare to cast a sorcery.<br>Follow up with a normal attack to cast the Night Comet sorcery, or a strong attack to sweep forward with a burst of flames.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黄金波动</p><br>专用战技：黄金波动<br><br>将剑身寄宿旧时的黄金，接着释放的战技。<br>黄金波动会朝前方扇状大幅扩散，<br>横扫所有敌人。</div><div class="t"><p>黄金波</p><br>専用戦技「黄金波」<br><br>剣身に往時の黄金を宿し、放つ戦技<br>黄金の波は、前方扇状に大きく広がり<br>あらゆる敵を薙ぎ払う<br></div><div class="t"><p>Wave of Gold</p><br>Unique Skill: Wave of Gold<br><br>Imbue the sword with bygone golden glory, then fire it at foes.<br>A wide, golden wave fans out forwards, sweeping through all enemies caught in its path.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>毁灭灵火</p><br>专用战技：毁灭灵火<br><br>挥动剑，让剑身缠绕灵火的战技。<br>灵火能给予魔力属性伤害。<br>此外，灵火非常地冰冷。</div><div class="t"><p>滅びの霊炎</p><br>専用戦技「滅びの霊炎」<br><br>剣を振り、その刀身に霊炎を纏わせる戦技<br>霊炎は魔力属性のダメージを与え<br>また、とても冷たい<br></div><div class="t"><p>Ruinous Ghostflame</p><br>Unique Skill: Ruinous Ghostflame<br><br>Swing the sword to bathe its blade in ghostflame.<br>The ghostflame adds magic damage to attacks, and also has a bitterly cold bite.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>高举黄金律法</p><br>专用战技：高举黄金律法<br><br>敬礼的同时高举武器，<br>形成黄金爆炸的战技。<br>再次发动，能释放黄金光波。</div><div class="t"><p>黄金律掲揚</p><br>専用戦技「黄金律掲揚」<br><br>敬礼と共に武器を掲揚し<br>黄金の炸裂を生じる戦技<br>追加入力で、黄金の光波を放つ<br></div><div class="t"><p>Establish Order</p><br>Unique Skill: Establish Order<br><br>Raise the armament in a salute, releasing a golden explosion.<br>Repeated inputs send out waves of golden light.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>催眠烟雾</p><br>专用战技：催眠烟雾<br><br>朝前方形成大范围淡紫色烟雾的战技。<br>淡紫色烟雾具有引发异常状态催眠的效果。</div><div class="t"><p>眠りの霧</p><br>専用戦技「眠りの霧」<br><br>前方広範囲に、薄紫の霧を生じる戦技<br>その霧には、睡眠の状態異常効果がある<br></div><div class="t"><p>Mists of Slumber</p><br>Unique Skill: Mists of Slumber<br><br>Releases a faint purple mist that spreads across a wide frontwards area.<br>This mist inflicts the sleep ailment upon foes.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>唤矛仪式</p><br>专用战技：唤矛仪式<br><br>祈祷的同时高举矛，指向天空，<br>召唤倾注而下的无数灵矛的战技。</div><div class="t"><p>槍呼びの儀</p><br>専用戦技「槍呼びの儀」<br><br>祈りと共に槍を空に突き上げ<br>降り注ぐ、無数の霊槍を呼ぶ戦技<br></div><div class="t"><p>Spearcall Ritual</p><br>Unique Skill: Spearcall Ritual<br><br>Thrust the spear high, bearing prayers into the sky to summon a downpour of spectral spears.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>狼袭</p><br>专用战技：狼袭<br><br>剑身缠绕寒气，一边旋身一边向前跳，<br>再顺势将大剑刺入地面的战技。<br>拔起大剑的同时，会引发寒气爆炸。</div><div class="t"><p>狼の襲撃</p><br>専用戦技「狼の襲撃」<br><br>剣身に冷気を纏い、回転しながら前方に跳躍し<br>その勢いのまま、大剣を地に突き立てる戦技<br>それを引き抜く時、冷気の爆発を伴う<br></div><div class="t"><p>Wolf's Assault</p><br>Unique Skill: Wolf's Assault<br><br>Infuse the greatsword with frost, then perform a forward somersault to plunge it into the ground. Then, pull it out to release a cold blast.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>雷云化身</p><br>专用战技：雷云化身<br><br>自己暂时化为红色雷云，飞上空中，<br>再用缠绕雷电的剑身贯穿敌人的战技。<br>持续发动能增加在空中移动的距离。</div><div class="t"><p>雷雲の姿</p><br>専用戦技「雷雲の姿」<br><br>自らの姿を一時赤い雷雲と化し<br>空を駆け、雷を纏った剣身で貫く戦技<br>長押しで、空を駆ける距離が伸びる<br></div><div class="t"><p>Thundercloud Form</p><br>Unique Skill: Thundercloud Form<br><br>Temporarily transform into a red thundercloud and fly through the air, then plunge down with a lightning-infused blade.<br>Hold to increase the reach of the thundercloud form.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>咒血斩击</p><br>专用战技：咒血斩击<br><br>摆出架式后一口气向前冲，使出下砍的战技。<br>下砍后的鲜血剑光会伴随较晚引发的火焰爆炸。<br>再次发动能使出追击。</div><div class="t"><p>呪血の斬撃</p><br>専用戦技「呪血の斬撃」<br><br>構えから一気に踏み込み、斬り下ろす戦技<br>その血の剣閃は、一瞬遅れて炎の爆発を伴う<br>また、追加入力で追撃に繋げられる<br></div><div class="t"><p>Cursed-Blood Slice</p><br>Unique Skill: Cursed-Blood Slice<br><br>Brace, then charge forward to deliver a downward diagonal slice.<br>The bloody trail of the blade is followed by a burst of flame.<br>Additional input allows for a follow-up attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>水鸟乱舞</p><br>专用战技：水鸟乱舞<br><br>犹如水鸟般单脚跳跃，<br>再使出超高速连斩的战技。<br>再次发动，能使出最多两次的追击。</div><div class="t"><p>水鳥乱舞</p><br>専用戦技「水鳥乱舞」<br><br>水鳥のごとく一本足で跳び<br>超高速の連続斬りに繋げる戦技<br>追加入力で、二度まで追撃に繋げられる<br></div><div class="t"><p>Waterfowl Dance</p><br>Unique Skill: Waterfowl Dance<br><br>Perform a series of one-footed leaps in the manner of a waterfowl to unleash a swift yet graceful slashing combo.<br>Repeated inputs allow for up to two follow-up attacks.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黄金碎击</p><br>专用战技：黄金碎击<br><br>轻盈跳起，让卢恩碎片蕴藏光芒，<br>再从空中用力敲下的战技。<br>拉达冈英雄般的敲击。</div><div class="t"><p>黄金砕き</p><br>専用戦技「黄金砕き」<br><br>ふわりと跳躍し、ルーンの破片に光を宿し<br>それを空中から、思い切り叩きつける戦技<br>ラダゴンの英雄的殴打<br></div><div class="t"><p>Gold Breaker</p><br>Unique Skill: Gold Breaker<br><br>Leap up high and, while suspended in midair, imbue the rune shard with light before smashing it down hard onto the ground.<br>The heroic Radagon's signature attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>跪下吧！</p><br>专用战技：跪下吧！<br><br>将王斧连续刺向地面，产生冲击波之余，<br>也撼动地面两次的战技。<br>再次发动，能再一次剧烈撼动地面。</div><div class="t"><p>地に伏せよ！</p><br>専用戦技「地に伏せよ！」<br><br>王斧を地面に連続で突き立て<br>衝撃波と共に、大地を二度揺らす戦技<br>追加入力で、もう一度激しく大地を揺らす<br></div><div class="t"><p>I Command Thee, Kneel!</p><br>Unique Skill: I Command Thee, Kneel!<br><br>Repeatedly smash the Axe of Godrick into the ground, unleashing two earth-shaking shockwaves.<br>Follow up with an additional input to produce a third shockwave.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>王者嘶吼</p><br>专用战技：王者嘶吼<br><br>发出嘶吼，提升攻击力的战技。<br>踏地时的冲击波无法用防御挡下。<br>在战技有效时间内，<br>重攻击会变成前踏斩击。</div><div class="t"><p>王の雄叫び</p><br>専用戦技「王の雄叫び」<br><br>雄叫びを上げ、攻撃力を高める戦技<br>大地を踏む衝撃波はガードすることができず<br>効果中、強攻撃が踏み込み斬りとなる<br></div><div class="t"><p>Regal Roar</p><br>Unique Skill: Regal Roar<br><br>Let loose a mighty war cry, raising attack power, while sending out a shockwave that cannot be guarded against by stomping the ground. While active, strong attack becomes a lunging slash.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>唤星</p><br>专用战技：唤星<br><br>双剑交错、指向天空的同时发出嘶吼，<br>利用重力波拉近敌人的战技。<br>再次发动，能用缠绕重力的剑使出敲击。</div><div class="t"><p>星呼び</p><br>専用戦技「星呼び」<br><br>両の剣を合わせた後、空に雄叫び<br>重力波により、敵を引き寄せる戦技<br>追加入力で、重力を纏った剣を叩きつける<br></div><div class="t"><p>Starcaller Cry</p><br>Unique Skill: Starcaller Cry<br><br>Bring the two swords together and roar into the skies, pulling in enemies with a gravitational wave.<br>Follow up with an additional input to slam down with gravity-infused swords.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>崩坏波</p><br>专用战技：崩坏波<br><br>高举剑之后向下敲，<br>释放于地面爬行的重力波的战技。</div><div class="t"><p>崩壊波</p><br>専用戦技「崩壊波」<br><br>剣を掲げた後、それを叩きつけ<br>地を走る重力波を放つ戦技<br></div><div class="t"><p>Wave of Destruction</p><br>Unique Skill: Wave of Destruction<br><br>Raise the sword up high, then strike it against the ground to fire off a wave of gravitational force.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>授血仪式</p><br>专用战技：授血仪式<br><br>高举圣矛，刺进无形之母体内的战技。<br>最多能刺三次，每次都会引发鲜血爆炸。<br>缠绕圣矛上的血焰会暂时延续。</div><div class="t"><p>血授の儀</p><br>専用戦技「血授の儀」<br><br>聖槍を掲げ、姿なき母の身体を刺す戦技<br>三度まで刺し、刺す度に血の爆発を生じる<br>聖槍は血炎を纏い、それはしばらく継続する<br></div><div class="t"><p>Bloodboon Ritual</p><br>Unique Skill: Bloodboon Ritual<br><br>Raise the sacred spear and pierce the body of the Formless Mother. Stab up to three times, creating explosions of blood with each thrust.<br>This skill will coat the armament with bloodflame for a while.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>流体化</p><br>专用战技：流体化<br><br>让武器暂时化为流体的战技。<br>能大幅挥动，大范围横扫敌人，<br>再用泪滴状的打击部位向下敲。</div><div class="t"><p>流体化</p><br>専用戦技「流体化」<br><br>武器を一時的に流体となす戦技<br>大きく振り回し、周囲を薙ぎ払った後<br>滴状の打撃部を叩きつける<br></div><div class="t"><p>Flowing Form</p><br>Unique Skill: Flowing Form<br><br>Temporarily transforms armament into its liquid form. Swing the armament like a whip to strike surroundings before slamming its teardrop-shaped head down.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>死亡刀刃</p><br>专用战技：死亡刀刃<br><br>解放死亡卢恩的力量，<br>将力量化为刀刃后释放的战技。<br>给予敌人伤害的同时，也会减少血量上限，<br>并且在一定时间内，血量会持续减少。</div><div class="t"><p>死の刃</p><br>専用戦技「死の刃」<br><br>死のルーンの力を解放し、刃となして放つ戦技<br>ダメージを与えると共に、最大ＨＰを減少させ<br>しばらくの間ＨＰを削り続ける<br></div><div class="t"><p>Blade of Death</p><br>Unique Skill: Blade of Death<br><br>Unleash the power of the Rune of Death to fire off a blade-like projectile.<br>In addition to dealing immediate damage, the blade reduces the enemy's maximum HP and continues to wear down HP for a while.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黄金刀刃</p><br>专用战技：黄金刀刃<br><br>跳至空中，让武器缠绕黄金火焰，<br>将火焰化为刀刃后释放的战技。<br>能给予圣属性伤害。</div><div class="t"><p>黄金の刃</p><br>専用戦技「黄金の刃」<br><br>宙に跳び、武器に黄金の炎を纏わせ<br>それを刃となして放つ戦技<br>聖属性のダメージを与える<br></div><div class="t"><p>Blade of Gold</p><br>Unique Skill: Blade of Gold<br><br>Leap into the air, charging the armament with golden flames that are then shot at the enemy as a single, blade-like projectile.<br>Inflicts holy damage.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>命定之死</p><br>专用战技：命定之死<br><br>解放命定之死残留的碎屑，<br>将大剑刺向地面，形成无数刀刃的战技。<br>给予敌人伤害的同时，也会减少血量上限，<br>并且在短暂时间内，血量会些微持续减少。</div><div class="t"><p>運命の死</p><br>専用戦技「運命の死」<br><br>運命の死、その残滓を解放し<br>大剣を地に突き立て、無数の刃を生じる戦技<br>ダメージを与えると共に、最大ＨＰを減少させ<br>ごく短時間の間、ＨＰを細かく削り続ける<br></div><div class="t"><p>Destined Death</p><br>Unique Skill: Destined Death<br><br>Set free the remnants of Destined Death, plunging the greatsword into the ground to summon a myriad of blades. In addition to dealing immediate damage, this attack reduces the enemy's maximum HP and continues to wear down HP for a short time.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>旋转刺轮</p><br>专用战技：旋转刺轮<br><br>摩擦地面，让刺轮高速旋转的战技。<br>持续发动能让刺轮维持高速旋转，<br>也能直接移动，将刺轮推向敌人。</div><div class="t"><p>車輪回転</p><br>専用戦技「車輪回転」<br><br>地面を擦り、高速で車輪を回転させる戦技<br>長押しで、高速回転状態を維持することができ<br>そのまま歩き、敵に車輪を押し当てることもできる<br></div><div class="t"><p>Spinning Wheel</p><br>Unique Skill: Spinning Wheel<br><br>Strike the wheel against the ground to set it spinning at top speed. Hold to keep the wheel spinning. Can be used while walking to push the armament into enemies.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>白王引力波</p><br>专用战技：白王引力波<br><br>将武器刺入地面，产生重力波，<br>能给予敌人伤害，同时将对方拉近自己的战技。<br>与战技“重力”相比，有效范围更广。</div><div class="t"><p>白王の引力波</p><br>専用戦技「白王の引力波」<br><br>武器を地面に刺し、重力波を発生させ<br>ダメージを与えると共に、敵を引き寄せる戦技<br>「グラビタス」よりも有効範囲が広い<br></div><div class="t"><p>Alabaster Lords' Pull</p><br>Unique Skill: Alabaster Lord's Pull<br><br>Thrust the armament into the ground to create a gravity well. In addition to dealing damage, this attack pulls enemies in.<br>Has a greater area of effect than Gravitas.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黑王推力波</p><br>专用战技：黑王推力波<br><br>将武器刺入地面，产生重力波，<br>能给予敌人伤害，同时将对方弹飞的战技。</div><div class="t"><p>黒王の斥力波</p><br>専用戦技「黒王の斥力波」<br><br>武器を地面に刺し、重力波を発生させ<br>ダメージを与えると共に、敵を弾き飛ばす戦技<br></div><div class="t"><p>Onyx Lords' Repulsion</p><br>Unique Skill: Onyx Lord's Repulsion<br><br>Thrust the armament into the ground to create a gravity well. In addition to dealing damage, this attack sends enemies flying away.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>复仇誓言</p><br>专用战技：复仇誓言<br><br>对大剑立下为一族复仇的誓言，<br>一定时间内，提升所有能力值的战技。<br>在立誓的那一瞬间，也会提升强韧度。</div><div class="t"><p>復讐の誓い</p><br>専用戦技「復讐の誓い」<br><br>大剣に一族の復讐を誓い<br>一定時間、すべての能力値を高める戦技<br>誓いの瞬間は、強靭度も高まっている<br></div><div class="t"><p>Oath of Vengeance</p><br>Unique Skill: Oath of Vengeance<br><br>Swear an oath upon the greatsword to avenge the clan, temporarily raising all attributes for a certain duration. While the oath's effects are active, poise will also be increased.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>冰雷剑</p><br>专用战技：冰雷剑<br><br>高举刀身召唤冰雷，再一斩而下的战技。<br>缠绕刀身上的冰雷会暂时延续。</div><div class="t"><p>氷雷剣</p><br>専用戦技「氷雷剣」<br><br>掲げた刀身に氷雷を呼び、斬り下ろす戦技<br>刃に纏う氷雷は、しばらく継続する<br></div><div class="t"><p>Ice Lightning Sword</p><br>Unique Skill: Ice Lightning Sword<br><br>Call down a bolt of ice lightning into the blade and bring it down upon a foe.<br>The ice lightning effect will persist for a while.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>兽王爪</p><br>专用战技：兽王爪<br><br>将大锤敲向地面，<br>让五只兽爪大幅撕裂大地的战技。</div><div class="t"><p>獣王の爪</p><br>専用戦技「獣王の爪」<br><br>大槌を地面に叩きつけ<br>五本の獣爪で、大地を大きく引き裂く戦技<br></div><div class="t"><p>Regal Beastclaw</p><br>Unique Skill: Regal Beastclaw<br><br>Slam the hammer into the ground, rending the land asunder with the armament's five bestial claws.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>弹指</p><br>专用战技：弹指<br><br>让手指膨胀变大，弯曲蓄满力量，<br>再用指尖弹飞敌人的战技。</div><div class="t"><p>爪弾き</p><br>専用戦技「爪弾き」<br><br>指を膨張させると共に、折り曲げて力をため<br>爪先で敵を弾き飛ばす戦技<br></div><div class="t"><p>Claw Flick</p><br>Unique Skill: Claw Flick<br><br>Cause the finger to swell, then flex to build up strength before giving enemies an almighty flick.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>星云</p><br>专用战技：星云<br><br>对弃子的星星们灌入魔力，<br>使出横扫攻击的同时，形成黑暗星云的战技。<br>星云会在短时间内爆炸消失。</div><div class="t"><p>星雲</p><br>専用戦技「星雲」<br><br>落とし子の星屑に魔力を込め<br>薙ぎ払う攻撃と共に、暗黒の星雲を生じる戦技<br>星雲は、一瞬の後、爆発して消える<br></div><div class="t"><p>Nebula</p><br>Unique Skill: Nebula<br><br>Imbue the Naturalborn's stars with magic to perform a sweeping strike.<br>This attack leaves a dark cloud of stars in its wake that lingers briefly before exploding.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>点燃灵火</p><br>专用战技：点燃灵火<br><br>从钩状前端产生灵火的战技。<br>发动后接着使出轻攻击，能释放爬行地面的灵火。<br>使出重攻击能引爆灵火，形成大爆炸。</div><div class="t"><p>霊炎発火</p><br>専用戦技「霊炎発火」<br><br>突き出した鉤棒の先に、霊炎を生じる戦技<br>通常攻撃で、霊炎を地に這わせて放ち<br>強攻撃で、それを大きく爆発させる<br></div><div class="t"><p>Ghostflame Ignition</p><br>Unique Skill: Ghostflame Ignition<br><br>Thrust out the barbed rod and set its tip alight with ghostflame.<br>Follow up with a normal attack to set the ground ablaze with ghostflame, or a strong attack to trigger a massive explosion.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>古雷电枪</p><br>专用战技：古雷电枪<br><br>将古龙的武器──红色雷电缠绕在武器上，<br>再将雷电化成枪，投掷而出的战技。<br>借由蓄力发动，能提升威力。</div><div class="t"><p>古雷の槍</p><br>専用戦技「古雷の槍」<br><br>古竜の武器たる赤い雷を武器に纏い<br>それを、槍となして投擲する戦技<br>タメ使用で強化される<br></div><div class="t"><p>Ancient Lightning Spear</p><br>Unique Skill: Ancient Lightning Spear<br><br>Imbue the armament with the ancient dragons' red lightning, then throw it as a spear.<br>Can be charged to increase its power.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>癫火突击</p><br>专用战技：癫火突击<br><br>将癫火缠绕矛之后向前跳，<br>向下刺出的同时，引发剧烈爆炸的战技。<br>施放者也会累积发狂量表。</div><div class="t"><p>狂い火突き</p><br>専用戦技「狂い火突き」<br><br>狂い火を槍に纏い、前方に跳躍し<br>突き下ろしと共に、激しい爆発を生じる戦技<br>この戦技は、使用者にも発狂を蓄積する<br></div><div class="t"><p>Frenzyflame Thrust</p><br>Unique Skill: Frenzyflame Thrust<br><br>Imbue the spear with the flame of frenzy and leap forwards, plunging it into the ground and setting off a maddening explosion.<br>The skill inflicts both the enemy and the user with madness.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>米凯拉的光环</p><br>专用战技：米凯拉的光环<br><br>形成米凯拉的闪耀光环，再向前释放的战技。<br>可以连续施放。</div><div class="t"><p>ミケラの光輪</p><br>専用戦技「ミケラの光輪」<br><br>ミケラの輝く光輪を生じ、前方に放つ戦技<br>連続で放つことができる<br></div><div class="t"><p>Miquella's Ring of Light</p><br>Unique Skill: Miquella's Ring of Light<br><br>Summon Miquella's shining halo and fire it forwards.<br>Can be fired in rapid succession.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黄金剑技</p><br>专用战技：黄金剑技<br><br>将两把剑交叉，附加圣属性攻击力的战技。<br>在战技有效时间内，<br>重攻击会变成双剑连击。</div><div class="t"><p>黄金の剣技</p><br>専用戦技「黄金の剣技」<br><br>二つの剣を交差させ、聖属性の攻撃力を付与する戦技<br>効果中、強攻撃が二刀の連撃となる<br></div><div class="t"><p>Golden Tempering</p><br>Unique Skill: Golden Tempering<br><br>Cross the two swords to grant their attacks holy essence.<br>While in effect, strong attack performs a dual-wielding combo attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>哀悼墓碑</p><br>专用战技：哀悼墓碑<br><br>高举墓碑，包含周围我方人物<br>附加圣律力量的战技。<br>对死诞者的哀悼效果特别卓越。</div><div class="t"><p>弔いの墓標</p><br>専用戦技「弔いの墓標」<br><br>墓標を掲げ、周囲の味方を含め<br>聖律の力を付与する戦技<br>死に生きる者たちを良く弔う<br></div><div class="t"><p>Last Rites</p><br>Unique Skill: Last Rites<br><br>Raise the epitaph to grant the effect of Sacred Order to yourself and allies in the vicinity.<br>Particularly effective at laying to rest Those Who Live in Death.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>不可挡之刃</p><br>专用战技：不可挡之刃<br><br>让秘文剑刃蕴藏光芒，<br>增加剑身长度，使出大范围斩击的战技。<br>此攻击无法用防御挡下。</div><div class="t"><p>防ぎ得ぬ刃</p><br>専用戦技「防ぎ得ぬ刃」<br><br>秘文字の刃に光を宿し、その長さを増し<br>一気に広範囲を斬り払う戦技<br>この攻撃をガードすることはできない<br></div><div class="t"><p>Unblockable Blade</p><br>Unique Skill: Unblockable Blade<br><br>Imbue the cipher blade with light, extending its length, then strike with a sudden sweeping attack.<br>This attack cannot be blocked.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>欧赫剑舞</p><br>专用战技：欧赫剑舞<br><br>把气灌入剑中，旋转之后朝前方释放的战技。<br>整把剑会剧烈旋转，给予连续损伤。<br>借由蓄力发动，能提升飞翔距离与旋转时间。</div><div class="t"><p>エオヒドの剣舞</p><br>専用戦技「エオヒドの剣舞」<br><br>剣に気を宿し、捻りを加え前方に放つ戦技<br>その剣は激しく回転し、連続でダメージを与える<br>タメ使用で飛距離を増し、回転の持続時間も増す<br></div><div class="t"><p>Eochaid's Dancing Blade</p><br>Unique Skill: Eochaid's Dancing Blade<br><br>Infuse the sword with energy, then fling it forwards in a corkscrew attack. The sword continuously deals damage while violently spinning.<br>Charge the attack to increase reach and duration of the spin.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>尸蜡斩击</p><br>专用战技：尸蜡斩击<br><br>古英雄们的失传战技。<br>高举剑身，解放尸蜡的力量，<br>将力量化为刀刃，朝前方释放。</div><div class="t"><p>死蝋斬り</p><br>専用戦技「死蝋斬り」<br><br>古い英雄たちの失われた戦技<br>高く掲げた剣身に、死蝋の力を開放し<br>それを刃として前方に放つ<br></div><div class="t"><p>Corpse Wax Cutter</p><br>Unique Skill: Corpse Wax Cutter<br><br>Lost skill of ancient heroes.<br>Lift the sword up high to release the power of corpse wax and launch it forwards as a blade-like projectile.<br></div></div>
<div class="pa"><div class="i"></div><div class="t"><p>萨米尔冰风暴</p><br>专用战技：萨米尔冰风暴<br><br>将弯刀刺入地面，向下使力，<br>在周围形成寒气风暴的战技。</div><div class="t"><p>ザミェルの氷嵐</p><br>専用戦技「ザミェルの氷嵐」<br><br>湾刀を地に刺し、力を込め<br>周囲に冷気の嵐を生じる戦技<br></div><div class="t"><p>Zamor Ice Storm</p><br>Unique Skill: Zamor Ice Storm<br><br>Plunge the curved sword into the ground, building power before unleashing a freezing storm that batters the surroundings.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>拉塔恩的骤雨</p><br>专用战技：拉塔恩的骤雨<br><br>压低身形拉弓的战技。<br>摆出架式后，朝天空一口气射出大量的箭，<br>箭会如骤雨一般，从敌人上方倾注而下。</div><div class="t"><p>ラダーンの驟雨</p><br>専用戦技「ラダーンの驟雨」<br><br>低い姿勢で弓を構える戦技<br>構えながら、多数の矢を一気に空に射る<br>それは、驟雨のごとく敵に降り注ぐ<br></div><div class="t"><p>Radahn's Rain</p><br>Unique Skill: Radahn's Rain<br><br>Archery skill performed from a low stance.<br>Ready the bow and fire a sudden flurry of arrows up into the sky. The arrows will pour on foes like rain.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>女王黑焰</p><br>专用战技：女王黑焰<br><br>在剑身点燃狩猎神祇的黑焰，<br>使出斩击的战技。再次发动能使出追击。<br>黑焰会在一定时间内，让血量持续减少。</div><div class="t"><p>女王の黒炎</p><br>専用戦技「女王の黒炎」<br><br>剣身に神狩りの黒炎を燃やし、斬り払う戦技<br>追加入力で追撃に繋げられる<br>また黒炎は、しばらくの間ＨＰを削り続ける<br></div><div class="t"><p>The Queen's Black Flame</p><br>Unique Skill: The Queen's Black Flame<br><br>Set the blade ablaze with the god-slaying black flame before delivering a sweeping slash. Additional input allows for a follow-up attack. The black flames will continue to wear down HP for a while.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>王朝剑技</p><br>专用战技：王朝剑技<br><br>优雅地闪避攻击，与敌人拉开距离的战技。<br>发动后接着使出重攻击，<br>能一口气向前推进，突刺攻击。<br>再次使出重攻击，能横扫攻击。</div><div class="t"><p>王朝剣技</p><br>専用戦技「王朝剣技」<br><br>華麗に攻撃を回避し、敵と距離を取る戦技<br>強攻撃で、一気に前進する突きに繋げられ<br>更なる強攻撃は斬り払いとなる<br></div><div class="t"><p>Dynast's Finesse</p><br>Unique Skill: Dynast's Finesse<br><br>Nimbly avoid an attack, securing some distance from foes. Follow up with strong attack to perform a sudden lunge, and press strong attack again to perform a sweeping slice.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>泼洒熔岩</p><br>专用战技：泼洒熔岩<br><br>旋身砍向敌人的同时，<br>朝周围喷洒熔岩的战技。<br>再次发动能使出追击。</div><div class="t"><p>溶岩撒き</p><br>専用戦技「溶岩撒き」<br><br>体を回転させて敵を斬りつけながら<br>周囲に、溶岩を撒き散らす戦技<br>追加入力で追撃に繋げられる<br></div><div class="t"><p>Magma Shower</p><br>Unique Skill: Magma Shower<br><br>Slash at foes in a twirling motion while scattering magma all around.<br>Additional input allows for a follow-up attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>星云</p><br>专用战技：星云<br><br>对弃子的薄翼灌入魔力，<br>在前方形成黑暗星云的战技。<br>星云会在短时间内爆炸消失。</div><div class="t"><p>星雲</p><br>専用戦技「星雲」<br><br>落とし子の薄羽に魔力を込め<br>前方に、暗黒の星雲を生じる戦技<br>星雲は、一瞬の後、爆発して消える<br></div><div class="t"><p>Nebula</p><br>Unique Skill: Nebula<br><br>Imbue the Naturalborn's wings with magic to send forth a dark cloud of stars that lingers briefly before exploding.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>死亡闪焰</p><br>专用战技：死亡闪焰<br><br>让失色的太阳蕴藏死王子火焰的战技。<br>能够引发异常状态死亡。<br>再次发动能使出下砍，引爆火焰。</div><div class="t"><p>死のフレア</p><br>専用戦技「死のフレア」<br><br>色を失くした太陽に、死王子の炎を宿す戦技<br>それは、死の状態異常効果を持つ<br>追加入力で斬り下ろし、炎を爆発させる<br></div><div class="t"><p>Death Flare</p><br>Unique Skill: Death Flare<br><br>Set the lusterless sun ablaze with the Prince of Death's flames, inflicting the death ailment upon foes.<br>Follow up with an additional input to bring down the armament, triggering an explosion.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>猎犬剑技</p><br>专用战技：猎犬剑技<br><br>用长牙大幅上砍的同时，<br>旋身与敌人拉开距离的战技。<br>发动后接着使出重攻击，<br>能踩出“猎犬步法”向前追击。</div><div class="t"><p>猟犬の剣技</p><br>専用戦技「猟犬の剣技」<br><br>長牙を大きく斬り上げながら<br>回転して敵との距離を取る戦技<br>強攻撃で、猟犬のステップからの追撃を行う<br></div><div class="t"><p>Bloodhound's Finesse</p><br>Unique Skill: Bloodhound's Finesse<br><br>Slash upwards with the Bloodhound's Fang, using the momentum of the strike to perform a backwards somersault and gain some distance from foes. Follow up with a strong attack to perform the Bloodhound's Step attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>熔岩断首</p><br>专用战技：熔岩断首<br><br>横摆鳞剑、剑锋下转往前跳，<br>向下敲击的同时，引爆熔岩的战技。<br>再次发动能使出拉近追击。</div><div class="t"><p>溶岩ギロチン</p><br>専用戦技「溶岩ギロチン」<br><br>鱗剣を咥えるように持ち、前方に跳躍して<br>叩き付けと共に、溶岩の爆発を生じる戦技<br>追加入力で、引き斬りの追撃を行う<br></div><div class="t"><p>Magma Guillotine</p><br>Unique Skill: Magma Guillotine<br><br>Grab the scalesword with both hands, as a wyrm would hold it in its mouth, and leap forwards, smashing it into the ground and triggering a blast of magma. Follow up with an additional input to perform a chopping attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>尸横遍野</p><br>战技：尸横遍野<br><br>将诅咒之血化为刀刃，<br>形成交叉连击的战技。<br>再次发动能使出更多连击。</div><div class="t"><p>死屍累々</p><br>専用戦技「死屍累々」<br><br>呪われた血を刃となし<br>交差する連撃を繰り出す戦技<br>追加入力で、更なる連撃に繋がる<br></div><div class="t"><p>Corpse Piler</p><br>Unique Skill: Corpse Piler<br><br>Forms a blade of cursed blood for repeated, interweaving successive attacks. Follow up with an additional input for further successive attacks. </div></div>
<div class="pa"><div class="i"></div><div class="t"><p>隙间月影</p><br>专用战技：隙间月影<br><br>收刀入腰间刀鞘，<br>摆出架式后静止不动的战技。<br>发动后接着使出轻攻击或重攻击，<br>能在高速斩击之余，也释放光波。</div><div class="t"><p>束の間の月影</p><br>専用戦技「束の間の月影」<br><br>刀身を鞘に収め、腰だめに静かに構える戦技<br>通常攻撃および強攻撃で、高速の斬撃に繋げ<br>それぞれ光波を放つ<br></div><div class="t"><p>Transient Moonlight</p><br>Unique Skill: Transient Moonlight<br><br>Sheathe blade, holding it at the hip in a composed stance.<br>Follow up with either a normal or a strong attack to draw the blade at great speed for an instant slash attack. Both attacks fire off a wave of light.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>米凯拉的奥秘剑</p><br>战技：米凯拉的奥秘剑<br><br>让米凯拉的庇佑蕴藏剑身之上，<br>对上死诞者能提升攻击力的战技。</div><div class="t"><p>ミケラの秘剣</p><br>戦技「ミケラの秘剣」<br><br>ミケラの加護を刀身に宿し<br>死に生きる者たちに対する攻撃力を高める戦技<br></div><div class="t"><p></p></div></div>
<div class="pa"><div class="i"></div><div class="t"><p>百智的世界</p><br>专用战技：百智的世界<br><br>高举权杖，在周围展开百智领域的战技。<br>包含自身与领域内的人物<br>降低魔力、圣属性减伤率。</div><div class="t"><p>百智の世界</p><br>専用戦技「百智の世界」<br><br>王笏を掲げ、周囲に百智の領域を展開する戦技<br>自らを含む、領域内のすべての者について<br>魔力および聖カット率が低下する<br></div><div class="t"><p>Knowledge Above All</p><br>Unique Skill: Knowledge Above All<br><br>Raise the scepter to manifest the realm of the All-Knowing. Enemy magic and holy damage negation will be reduced for all within the area, including the caster.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>吞世</p><br>专用战技：吞世<br><br>将灌入魔力的权杖伫立地面，<br>从周围所有敌人身上夺取血量的战技。</div><div class="t"><p>世界喰らい</p><br>専用戦技「世界喰らい」<br><br>魔力を込めた王笏を地に据え<br>周囲すべての敵から、ＨＰを奪う戦技<br></div><div class="t"><p>Devourer of Worlds</p><br>Unique Skill: Devourer of Worlds<br><br>Charge the scepter with magic and strike it against the ground to steal the HP of all nearby enemies.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>家族怨魂</p><br>专用战技：家族怨魂<br><br>一边轻晃红铜制的头颅，<br>一边召唤穷追不舍的怨魂群的战技。<br>妻与子的苦痛是怨魂作祟的源头。</div><div class="t"><p>家族の怨霊</p><br>専用戦技「家族の怨霊」<br><br>赤銅の首をゆっくりと揺らしながら<br>追いすがる怨霊たちを呼ぶ戦技<br>妻子の苦悶が、祟り招くのだ<br></div><div class="t"><p>Familial Rancor</p><br>Unique Skill: Familial Rancor<br><br>Gently rattle the copper heads to summon vengeful spirits that chase down foes.<br>The anguish of a spouse and children invites accursed wrath.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>罗泽司的唤声</p><br>专用战技：罗泽司的唤声<br><br>高举斧，召唤迷途死者们的战技。<br>三位死者会在远方现身，<br>配合施放者一起攻击后，消失踪影。</div><div class="t"><p>ローゼスの呼び声</p><br>専用戦技「ローゼスの呼び声」<br><br>斧を掲げ、死に迷う者たちを呼び出す戦技<br>三体が、離れた場所に呼び出され<br>召喚者に合わせて攻撃した後、消えてしまう<br></div><div class="t"><p>Rosus's Summons</p><br>Unique Skill: Rosus's Summons<br><br>Raise the axe aloft to summon those lost in death.<br>Three skeletons will appear at a distance and attack in tandem before vanishing.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>圣矛障壁</p><br>专用战技：圣矛障壁<br><br>释放蕴藏的祷告力量，<br>在前方展开黄金矛阵的战技。</div><div class="t"><p>聖槍の壁</p><br>専用戦技「聖槍の壁」<br><br>秘められた祈祷の力を解放し<br>前面に、黄金の槍衾を展開する戦技<br></div><div class="t"><p>Sacred Phalanx</p><br>Unique Skill: Sacred Phalanx<br><br>Release the power of a hidden incantation to erect a palisade of golden spears frontwards.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>狩猎大蛇</p><br>专用战技：狩猎大蛇<br><br>能全力突刺，再次发动后<br>会向上突刺攻击的战技。<br>对上大蛇时会产生长形光刃，<br>展现出真正的力量。</div><div class="t"><p>大蛇狩り</p><br>専用戦技「大蛇狩り」<br><br>全力で突き、追加入力で突き上げる戦技<br>大蛇と対した時、長き光の刃を生じ<br>真の力を発揮する<br></div><div class="t"><p>Great-Serpent Hunt</p><br>Unique Skill: Great-Serpent Hunt<br><br>Perform a powerful forward lunge and follow up with an upward thrust via additional input. When fighting a great serpent, a long blade of light will appear, revealing the armament's true power.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>天使羽翼</p><br>专用战技：天使羽翼<br><br>跳起的同时，让羽翼镰刃蕴藏白光，<br>再顺势斩下的战技。<br>白色羽翼能妨碍圣杯瓶的恢复效用。</div><div class="t"><p>天使の翼</p><br>専用戦技「天使の翼」<br><br>跳躍と共に、翼の刃に白い光を宿し<br>そのまま斬りつける戦技<br>白き翼は、聖杯瓶による回復を阻害する<br></div><div class="t"><p>Angel's Wings</p><br>Unique Skill: Angel's Wings<br><br>Jump and imbue the wing-blade of the armament with light, then deliver a slashing attack on the enemy.<br>The white wings impede recovery actions using a flask of tears.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>风暴踢击</p><br>专用战技：风暴踢击<br><br>将义足的刀刃刺入地面，形成风暴的战技。<br>发动后接着使出重攻击，<br>能让刀刃缠绕雷电，再跳跃攻击。</div><div class="t"><p>嵐蹴撃</p><br>専用戦技「嵐蹴撃」<br><br>義足の刃を地に突き立て、嵐を生じる戦技<br>強攻撃で、その刃に雷を纏った<br>跳躍攻撃に繋げられる<br></div><div class="t"><p>Storm Kick</p><br>Unique Skill: Storm Kick<br><br>Thrust the prosthetic leg blade into the ground, creating a storm.<br>Follow up with a strong attack to perform a lightning-infused jumping attack.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>不可挡之刃</p><br>专用战技：不可挡之刃<br><br>让秘文剑刃蕴藏光芒，<br>再一口气推进，贯穿敌人的战技。<br>此攻击无法用防御挡下。</div><div class="t"><p>防ぎ得ぬ刃</p><br>専用戦技「防ぎ得ぬ刃」<br><br>秘文字の刃に光を宿し<br>一気に前進して、刺し貫く戦技<br>この攻撃をガードすることはできない<br></div><div class="t"><p>Unblockable Blade</p><br>Unique Skill: Unblockable Blade<br><br>Imbue the cipher blade with light, then lunge forward with a sudden piercing attack.<br>This attack cannot be blocked.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>锡杖魔法</p><br>专用战技：锡杖魔法<br><br>将辉石灌入魔力，触发古老魔法的战技。<br>周围会出现自动飞向敌人的浮空魔法球。</div><div class="t"><p>錫杖の魔術</p><br>専用戦技「錫杖の魔術」<br><br>輝石に魔力を込め、古い魔術を発動する戦技<br>自律して対象に向かう魔法弾を、周囲に浮遊させる<br></div><div class="t"><p>Sorcery of the Crozier</p><br>Unique Skill: Sorcery of the Crozier<br><br>Channel magic into the glintstone to activate an ancient sorcery, producing floating magic projectiles that chase enemies automatically.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黄金树坠落震击</p><br>专用战技：黄金树坠落震击<br><br>轻盈向前跳，用臀部用力向下坠落，<br>引发黄金冲击波的战技。<br>在坠落震击的战技中，威力最为强大。</div><div class="t"><p>黄金樹の尻撃</p><br>専用戦技「黄金樹の尻撃」<br><br>ふわりと前方に跳躍し、重い尻を落とし<br>黄金の衝撃波を発生させる戦技<br>尻撃の中で、最も威力が高い<br></div><div class="t"><p>Erdtree Slam</p><br>Unique Skill: Erdtree Slam<br><br>Jump up high into the air and crash down on the ground ahead. The resulting pratfall sends golden shockwaves in all directions.<br>This is the most powerful of all the Ground Slam skills.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>重力雷电</p><br>专用战技：重力雷电<br><br>让星兽半颚蕴藏重力雷电，<br>借此在远方召唤落雷的战技。<br>可以连续施放。</div><div class="t"><p>重力雷</p><br>専用戦技「重力雷」<br><br>星獣の片顎に、重力の雷を宿し<br>離れた場所に、その落雷を呼ぶ戦技<br>連続で放つことができる<br></div><div class="t"><p>Gravity Bolt</p><br>Unique Skill: Gravity Bolt<br><br>Imbue the jaw of the fallingstar beast with gravitational lightning, sending a bolt crashing down a short distance away.<br>Can be fired in rapid succession.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>催眠火焰</p><br>专用战技：催眠火焰<br><br>吐气吹向烛台的火焰，用淡紫色的火焰<br>朝前方大范围横扫的战技。<br>具有引发异常状态催眠的效果。</div><div class="t"><p>眠りの炎</p><br>専用戦技「眠りの炎」<br><br>燭台の火に息を吹き付け<br>薄紫の火で、前方広範囲を焼き払う戦技<br>睡眠の状態異常効果がある<br></div><div class="t"><p>Fires of Slumber</p><br>Unique Skill: Fires of Slumber<br><br>Blow into the candlestick's flame, creating a stream of hazy purple fire to cover the ground ahead.<br>The intoxicating flames inflict the sleep ailment upon foes.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>黄金式奉还</p><br>专用战技：黄金式奉还<br><br>手持盾牌，释放守护祷告的战技。<br>能消除魔法、祷告的效用，以黄金力量奉还。</div><div class="t"><p>黄金の返報</p><br>専用戦技「黄金の返報」<br><br>盾を構え、守りの祈祷を解放する戦技<br>魔術や祈祷を消し去り、黄金の力を返報する<br></div><div class="t"><p>Golden Retaliation</p><br>Unique Skill: Golden Retaliation<br><br>Ready the shield to unleash its protective incantation.<br>This will dispel sorceries and incantations, retaliating with golden power.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>共鸣愤怒</p><br>专用战技：共鸣愤怒<br><br>诱发水母的愤怒，<br>让自己也感同身受的战技。<br>一定时间内，提升攻击力。</div><div class="t"><p>伝染する怒り</p><br>専用戦技「伝染する怒り」<br><br>クラゲの怒りを誘い<br>それを自らに伝染させる戦技<br>一定時間、攻撃力が高まる<br></div><div class="t"><p>Contagious Fury</p><br>Unique Skill: Contagious Fury<br><br>Incite the jellyfish's wrath and allow its fury to flow through you.<br>Raises attack power for a certain duration.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>奥陶琵斯的漩涡</p><br>专用战技：奥陶琵斯的漩涡<br><br>用熔炉的漩涡力量激烈旋转整个剑身，<br>再顺势敲向地面的战技。<br>借由蓄力发动，能提升威力。</div><div class="t"><p>オルドビスの渦</p><br>専用戦技「オルドビスの渦」<br><br>坩堝の渦の力で、剣全体を激しく回転させ<br>そのまま、大地に叩きつける戦技<br>タメ使用で強化される<br></div><div class="t"><p>Ordovis's Vortex</p><br>Unique Skill: Ordovis's Vortex<br><br>Channel the power of the crucible to spin the entire sword in midair, building momentum before slamming the blade down onto the ground.<br>This skill can be charged to increase its power.</div></div>
<div class="pa"><div class="i"></div><div class="t"><p>转啊转</p><br>专用战技：转啊转<br><br>将辉石灌入魔力，让权杖浮在自身前方<br>再高速旋转的战技。<br>触碰到的人物会受到魔力连击。</div><div class="t"><p>回れ回れ</p><br>専用戦技「回れ回れ」<br><br>輝石に魔力を込め、王笏を前方に浮かせ<br>それを高速に回転させる戦技<br>触れる者に、魔力の連撃をなす<br></div><div class="t"><p>Spinning Weapon</p><br>Unique Skill: Spinning Weapon<br><br>Channel magic into the glintstone to suspend the scepter in mid air and cause it to spin violently.<br>Those it touches will suffer successive magic attacks.</div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p></p></div><div class="t"><p>なし</p><br>-</div><div class="t"><p></p></div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p></p></div><div class="t"><p>回転薙ぎ</p><br>戦技「回転薙ぎ」<br><br>長柄の武器で、多勢に対するための戦技<br>大きく体を回転させて周囲の敵を薙ぎ払う<br>またその勢いを、強攻撃に繋げられる<br></div><div class="t"><p></p></div></div>
<div class="pa"><div class="i"><img class="im" src="~@img/00000.png"></div><div class="t"><p></p></div><div class="t"><p>不可視の矢</p><br>不可視の矢</div><div class="t"><p></p></div></div>
<div class="pa"><div class="i"></div><div class="t"><p></p></div><div class="t"><p>死蝶の舞</p><br>戦技「死蝶の舞」<br><br>魔力で召喚した死の蝶が敵に襲いかかる戦技<br>被弾した相手の生命力を奪い<br>使用者のHPを回復させる<br></div><div class="t"><p></p></div></div>
</div></template>

<style>
.pa {
  display: grid;
  grid-template-columns: 18% 22% 22% 22%;
  justify-content: space-between;
  border: 1px solid #e6ddbd;
  width: 100%;
  height: 100%;
  padding: 5px;
}
.i{
    justify-content: center; /* 水平居中 */
    position: relative;
}

.im{
    padding: 4px;
   position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  max-width: 100%; 
  max-height: 100%;
}
.t{
    padding: 5px;
};
</style>
